- .gitignore
- package.json
- pnpm-lock.yaml
- src/@types/web-ext.d.ts
- src/cli/commands/dev.ts
- src/index.ts
- src/runners/ExtensionRunner.ts
- src/runners/createWebExtRunner.ts
- src/types/external.ts
- src/types/internal.ts
- src/utils/defineRunnerConfig.ts
- src/utils/getInternalConfig.ts
> feat: Open browser when starting dev server

- demo/src/utils/logger.ts
- package.json
- pnpm-lock.yaml
- scripts/build.ts
- src/client/virtual-modules/fake-browser.ts
- src/core/build/__tests__/findEntrypoints.test.ts
- src/core/build/findEntrypoints.ts
- src/core/utils/getInternalConfig.ts
- src/core/utils/importTsFile.ts
- src/testing/fake-objects.ts
> fix: Unable to read entrypoint options

- src/core/build/generateTypesDir.ts
> feat: Add tsconfig path aliases

- demo/package.json
- package.json
- pnpm-lock.yaml
- scripts/build.ts
- src/@types/modules.d.ts
- src/cli/commands/index.ts
- src/cli/commands/zip.ts
- src/cli/index.ts
- src/core/log/printBuildSummary.ts
- src/core/log/printFileList.ts
- src/core/types/external.ts
- src/core/types/internal.ts
- src/core/utils/__tests__/strings.test.ts
- src/core/utils/getInternalConfig.ts
- src/core/utils/manifest.ts
- src/core/utils/package.ts
- src/core/utils/strings.ts
- src/core/zip.ts
- src/testing/fake-objects.ts
> feat: Add `wxt zip` command

- templates/react/_gitignore
- templates/react/entrypoints/popup/App.css
- templates/react/entrypoints/popup/App.tsx
- templates/react/package.json
- templates/solid/.npmrc
- templates/solid/_gitignore
- templates/solid/entrypoints/popup/App.css
- templates/solid/package.json
- templates/svelte/_gitignore
- templates/svelte/package.json
- templates/svelte/src/entrypoints/popup/App.svelte
- templates/vanilla/_gitignore
- templates/vanilla/entrypoints/popup/main.ts
- templates/vanilla/entrypoints/popup/style.css
- templates/vanilla/package.json
- templates/vue/_gitignore
- templates/vue/entrypoints/popup/App.vue
- templates/vue/package.json
1. Add `zip` commands to package.json
2. Change hover color to match WXT logo
3. Remove `artifacts` from `_gitignore`
4. Use path aliases for imports
5. Remove `.npmrc` files
> Cleanup templates

- src/cli/commands/build.ts
- src/cli/commands/dev.ts
- src/cli/commands/init.ts
- src/cli/commands/prepare.ts
- src/cli/commands/publish.ts
- src/cli/commands/zip.ts
- src/cli/index.ts
- src/cli/utils/defineCommand.ts
- src/core/types/external.ts
- src/core/types/internal.ts
- src/core/utils/getInternalConfig.ts
- src/core/vite-plugins/multipageMove.ts
- src/testing/fake-objects.ts
> feat: Add `--debug` flag for printing debug logs for all CLI commands

- package.json
- pnpm-lock.yaml
- src/@types/web-ext-run.d.ts
- src/core/runners/createWebExtRunner.ts
> feat: Replace `web-ext` with `web-ext-run`

- .gitignore
- .prettierignore
- docs/.vitepress/config.ts
- e2e/tests/output-structure.test.ts
- package.json
- pnpm-lock.yaml
- src/cli/commands/build.ts
- src/cli/index.ts
- src/core/build.ts
- src/core/types/external.ts
- src/core/types/internal.ts
- src/core/utils/getInternalConfig.ts
- src/core/vite-plugins/bundleAnalysis.ts
- src/core/vite-plugins/index.ts
- src/testing/fake-objects.ts
- templates/react/_gitignore
- templates/solid/_gitignore
- templates/svelte/_gitignore
- templates/vanilla/_gitignore
- templates/vue/_gitignore
> feat: `--analyze` build flag

- .github/workflows/validate.yml
- package.json
Add codecov and tweak the excluded file coverage.
> chore: Code coverage improvements

- docs/guide/content-scripts.md
- e2e/tests/manifest-content.test.ts
- src/core/server.ts
- src/core/types/external.ts
- src/core/utils/manifest.ts
> feat: Content script `cssInjectionMode`

- docs/entrypoints/popup.md
- src/core/build/findEntrypoints.ts
- src/core/types/external.ts
> fix: Add `browser_style` to popup options

- docs/guide/auto-imports.md
Amazing project. I am just testing it out for now, see if I'm going to have any issues with it.
> docs: Update auto-imports.md

- templates/react/README.md
- templates/svelte/README.md
Update React template and Svelte template README
> chore: Fix Svelte and React template READMEs

- docs/.vitepress/components/UsingWxtSection.vue
- docs/.vitepress/composables/useListExtensionDetails.ts
Add the rating and tweak the layout a little bit for better balance.
> docs: Improve the "Used By" section on homepage

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Add StayFree to homepage

- demo/src/entrypoints/background.ts
- demo/wxt.config.ts
- docs/.vitepress/config.ts
- docs/guide/compare.md
- docs/guide/storage.md
- docs/typedoc.json
- e2e/tests/auto-imports.test.ts
- package.json
- pnpm-lock.yaml
- scripts/build.ts
- src/__tests__/storage.test.ts
- src/core/utils/unimport.ts
- src/storage.ts
- src/virtual/background-entrypoint.ts
> feat: Add `wxt/storage` API

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Add Doozy to homepage

- .github/workflows/validate.yml
- templates/solid/package.json
> chore: Update sSolid template to vite 5

- bin/wxt.cjs
- bin/wxt.mjs
- package.json
- scripts/build.ts
- src/core/utils/building/get-internal-config.ts
- src/core/utils/building/import-entrypoint.ts
Another possible fix for #277?
This also reduces the build from `680.87 kB` to `594.79 kB`, 13% smaller!
> chore: Convert WXT CLI to an ESM binary

- e2e/tests/manifest-content.test.ts
- e2e/tests/output-structure.test.ts
- e2e/tests/typescript-project.test.ts
- e2e/tests/user-config.test.ts
- src/core/utils/building/__tests__/find-entrypoints.test.ts
- src/core/utils/building/find-entrypoints.ts
> fix: Throw error when no entrypoints are found

- package.json
- pnpm-lock.yaml
> fix: Upgrade `@webext-core/match-patterns` to `1.0.3`

- .github/workflows/validate.yml
- docs/.vitepress/components/UsingWxtSection.vue
- package.json
- pnpm-lock.yaml
> fix: Fix `package.json` lint errors

- src/core/builders/vite/plugins/noopBackground.ts
Addresses https://github.com/wxt-dev/wxt/pull/284#issuecomment-1868461589
> fix: Correct import in dev-only, noop background

- docs/entrypoints/devtools.md
> docs: Add example for setting up custom panels/panes in devtools

- README.md
- package.json
> chore: Re-enable coverage

- docs/.vitepress/components/UsingWxtSection.vue
Currently, I have decided to start rewriting my plugin using wxt, but this is just the beginning and it has not been completed yet.
> Upload a Chinese dubbing plugin for Youtube.

- src/cli.ts
ref: https://github.com/wxt-dev/wxt/pull/344#discussion_r1454391694
> fix: Make `getArrayFromFlags` result can be undefined

- src/__tests__/cli.test.ts
- src/cli.ts
> chore: Add unit tests for passing flags via the CLI

- src/core/utils/__tests__/manifest.test.ts
- src/core/utils/building/internal-build.ts
- src/core/utils/building/rebuild.ts
- src/core/utils/manifest.ts
- src/core/utils/testing/fake-objects.ts
> fix: Disable reload dev command when 4 commands are already registered

- docs/guide/content-script-ui.md
I continued to try today, but the documentation misled me again, so I modified it directly.
> docs: fix incorrect sample code

- src/core/utils/building/get-internal-config.ts
- src/core/utils/testing/fake-objects.ts
- src/core/zip.ts
- src/types/external.ts
- src/types/internal.ts
This PR resolves #377 
I am not sure is there a way to contact you somehow? Maybe Discord? 
Cause I'd like to learn if there's an easy way to test the source changes locally?
For this PR I did `pnpm run build` and then I linked from my test project the wxt source using `pnpm link ../wxt`
> feat(zip)!: add `includeSources` and rename `ignoredSources` to `excludeSources`

- src/core/builders/vite/plugins/__tests__/devHtmlPrerender.test.ts
- src/core/builders/vite/plugins/devHtmlPrerender.ts
- src/core/utils/testing/fake-objects.ts
Proof of concept. I am sure we can do better, but I just tried the simplest approach and it works fine. 
Resolves: #386
> fix(dev): Resolve `script` and `link` aliases

- docs/.vitepress/components/UsingWxtSection.vue
This PR adds PreMiD to the extensions list that proudly use wxt
> docs: Add premid extension to homepage

- docs/index.md
It is a very small contribution, but this typo is the first thing I saw when the website loaded.
> Fix typo on homepage hero section

- package.json
- src/core/create-server.ts
This closes #428.
https://github.com/wxt-dev/wxt/assets/10101283/ea1f1381-edbd-4003-b57a-a279c0a51038
> fix: Watch files outside project root during development

- docs/guide/content-script-ui.md
- src/core/create-server.ts
- src/core/utils/building/__tests__/find-entrypoints.test.ts
- src/core/utils/building/find-entrypoints.ts
- src/core/utils/content-scripts.ts
- src/core/utils/entrypoints.ts
- src/core/utils/manifest.ts
- src/types/index.ts
Types were structured poorly while I was looking into supporting #462. So I'm refactoring them.
> chore: Simplify entrypoint types

- docs/entrypoints/sidepanel.md
- src/core/utils/__tests__/manifest.test.ts
- src/core/utils/building/__tests__/find-entrypoints.test.ts
- src/core/utils/building/find-entrypoints.ts
- src/core/utils/manifest.ts
- src/core/utils/testing/fake-objects.ts
- src/types/index.ts
This closes #462. I also included a bit of a refactor to how options are extracted from HTML pages.
> feat: Support setting side panel options in HTML file

- e2e/tests/user-config.test.ts
- src/core/utils/building/resolve-config.ts
> fix: Respect `configFile` option

- e2e/tests/output-structure.test.ts
- src/core/create-server.ts
- src/types/index.ts
- src/virtual/background-entrypoint.ts
- src/virtual/utils/reload-content-scripts.ts
Additional dev mode improvements for #469
> fix: Improve dev mode for content scripts registered at runtime

- CHANGELOG.md
- CONTRIBUTING.md
- docs/entrypoints/background.md
- docs/entrypoints/css.md
- docs/entrypoints/sidepanel.md
- docs/guide/auto-imports.md
- docs/guide/compare.md
- docs/guide/configuration.md
- docs/guide/content-script-ui.md
- docs/guide/development.md
- docs/guide/entrypoints.md
- docs/guide/esm.md
- docs/guide/installation.md
- docs/guide/introduction.md
- docs/guide/migrate-to-wxt.md
- docs/guide/multiple-browsers.md
- docs/guide/publishing.md
- docs/index.md
- e2e/utils.ts
- src/storage.ts
- vitest.workspace.ts
Fixing a bunch of typos in docs and comments
> docs: Lots of small typo fixes

- docs/.vitepress/components/UsingWxtSection.vue
Add markdown sticky ntoes to docs website
> doc: add markdown sticky ntoes

- docs/.vitepress/components/UsingWxtSection.vue
Adding [DocVersionRedirector](https://github.com/leos/DocVersionRedirector/). If you have a few moments, would love a quick look at the code and any feedback on how I'm using WXT.
> docs: Added DocVersionRedirector to "Using WXT" section

- templates/react/entrypoints/content.ts
- templates/solid/entrypoints/content.ts
- templates/svelte/src/entrypoints/content.ts
- templates/vanilla/entrypoints/content.ts
- templates/vue/entrypoints/content.ts
> feat: Add basic content script to templates

- src/core/builders/vite/plugins/devHtmlPrerender.ts
- src/core/builders/vite/plugins/virtualEntrypoint.ts
- src/core/builders/vite/plugins/webextensionPolyfillMock.ts
- src/core/utils/building/import-entrypoint.ts
- src/core/utils/building/resolve-config.ts
- src/core/utils/testing/fake-objects.ts
- src/types/index.ts
Related to #457, quick refactor so the fix is a single line.
> feat: Add `ResolvedConfig.wxtModuleDir`, resolving the directory once

- package.json
- pnpm-lock.yaml
- src/core/package-managers/index.ts
- src/core/utils/testing/fake-objects.ts
- src/core/wxt.ts
- src/types/index.ts
> feat: Expose package management utils under `wxt.pm`

- src/core/package-managers/__tests__/npm.test.ts
Seeing intermittent failures for this test, so doubling the timeout.
https://github.com/wxt-dev/wxt/actions/runs/8141062062/job/22247529165
> chore: Increase test timeout for windows NPM tests

- templates/vue/.vscode/extensions.json
> fix: Remove deprecated extension

- docs/.vitepress/components/UsingWxtSection.vue
Adding [Plex skipper](https://github.com/GuiEpi/plex-skipper). Thank you for your high-quality framework!
> docs: Add Plex skipper to "Using WXT" section

- docs/guide/installation.md
- docs/guide/publishing.md
Hello, here is my little proposal to add Bun.sh in the current documentation.
- Installation 
- Publishing
I'll be happy to listen to any modifications, especially regarding the positioning in the code-group, where I'm not entirely sure.
> docs: Add documentation for Bun.sh

- docs/guide/development.md
This brings it up to date with the changes done in #362
> docs: Fixed "Reload the Extension" section

- docs/.vitepress/components/UsingWxtSection.vue
Add a new Github Custom Notifier extension
> docs: Add "GitHub Custom Notifier" to homepage

- src/cli/cli-utils.ts
- src/core/utils/arrays.ts
- src/core/utils/building/build-entrypoints.ts
- src/storage.ts
> chore: Add some array utils

- demo/src/entrypoints/background.ts
- demo/wxt.config.ts
- src/core/builders/vite/index.ts
> fix: Resolve absolute paths to the public directory properly

- README.md
- docs/.vitepress/config.ts
https://github.com/wxt-dev/wxt/discussions/587
> docs: Add discord server link

- src/client/content-scripts/ui/__tests__/index.test.ts
- src/client/content-scripts/ui/index.ts
This closes https://github.com/wxt-dev/wxt/issues/597
> fix(content-script-ui): Properly assign and unassign mounted value

- src/core/utils/__tests__/manifest.test.ts
- src/core/utils/manifest.ts
This closes https://github.com/wxt-dev/wxt/issues/602
> fix!: Automatically move `host_permissions` to `permissions` for MV2

- docs/guide/storage.md
advert to config permission before using storage
> docs: Document required permission for storage API

- docs/guide/testing.md
**PR Summary**:
PR #646 moved the location of the `wxt-vitest-plugin.ts` file. This PR adjusts sources to changes.
> docs: Fix `wxt-vitest-plugin` reference

- packages/wxt/src/core/utils/__tests__/manifest.test.ts
- packages/wxt/src/core/utils/testing/fake-objects.ts
> chore: Add missing tests for dev mode CSP

- packages/wxt/src/core/utils/__tests__/manifest.test.ts
- packages/wxt/src/core/utils/manifest.ts
> fix: Automatically add dev server to sandbox CSP

- docs/.vitepress/components/UsingWxtSection.vue
Adds demo.fun to wxt Using section
> docs: Adds demo.fun to homepage

- docs/.vitepress/components/UsingWxtSection.vue
Added SmartEReply: Elevate Your LinkedIn™ Engagement with AI 🚀📈 Chrome Extension
> docs: Add SmartEReply to homepage

- packages/wxt/src/__tests__/storage.test.ts
- packages/wxt/src/storage.ts
- pnpm-lock.yaml
This introduces new types that enforce the `area:key` format of storage keys by the WXT storage APIs.
> fix(storage): Add storage area typing for storage keys

- packages/wxt/vitest.config.ts
- pnpm-lock.yaml
This closes https://github.com/wxt-dev/wxt/security/dependabot/5.
> chore(deps): Upgrade braces to 3.0.3

- packages/wxt/e2e/tests/typescript-project.test.ts
- packages/wxt/src/core/utils/building/generate-wxt-dir.ts
- packages/wxt/src/core/utils/building/resolve-config.ts
- packages/wxt/src/types/index.ts
See https://github.com/wxt-dev/wxt/issues/717#issuecomment-2166246206 for more details.
> fix(modules): Add modules to TS project so type augmentation works

- packages/wxt/src/core/builders/vite/plugins/wxtPluginLoader.ts
> https://discord.com/channels/1212416027611365476/1250841232549347451
> fix(dev): Fix CSP error loading HTML plugins

- packages/module-svelte/README.md
- packages/module-svelte/package.json
- packages/module-svelte/src/index.ts
- packages/module-svelte/tsconfig.json
- pnpm-lock.yaml
Follow up to https://github.com/wxt-dev/wxt/pull/716. Still need to do Solid and React. React will be the difficult one.
> feat: Add `@wxt-dev/module-vue` package

- docs/guide/key-concepts/frontend-frameworks.md
Waiting to merge these new docs until the modules are released.
> docs: Update frontend framework docs with new modules

- packages/wxt/src/core/create-server.ts
- packages/wxt/src/core/utils/building/internal-build.ts
As mentioned in https://github.com/wxt-dev/wxt/pull/774#discussion_r1655267857, here's a small cleanup PR.
> chore: Replace consola with wxt.logger

- package.json
- pnpm-lock.yaml
See https://github.com/wxt-dev/wxt/pull/779
> chore: Upgrade `buildc` to v1.0.10

- templates/solid/package.json
Broke something in `@wxt-dev/module-solid@1.1.0`, so I'm testing out if the fix, 1.1.1, actually fixed it.
> Update solid template to `@wxt-dev/module-solid` v1.1.1

- docs/.vitepress/config.ts
- docs/guide/directory-structure/app-config.md
- packages/wxt-demo/src/app.config.ts
- packages/wxt-demo/src/entrypoints/background.ts
- packages/wxt/e2e/tests/__snapshots__/auto-imports.test.ts.snap
- packages/wxt/e2e/tests/auto-imports.test.ts
- packages/wxt/scripts/build.ts
- packages/wxt/src/client/app-config.ts
- packages/wxt/src/client/index.ts
- packages/wxt/src/core/builders/vite/index.ts
- packages/wxt/src/core/builders/vite/plugins/index.ts
- packages/wxt/src/core/builders/vite/plugins/resolveAppConfig.ts
- packages/wxt/src/core/utils/building/import-entrypoint.ts
- packages/wxt/src/sandbox/define-app-config.ts
- packages/wxt/src/sandbox/index.ts
- packages/wxt/src/testing/wxt-vitest-plugin.ts
> feat: Support runtime config in `app.config.ts`

- docs/.vitepress/components/UsingWxtSection.vue
Add the new plug-in "香草布丁🌿🍮" developed based on wxt。
chrome webstore:  https://chromewebstore.google.com/detail/%E9%A6%99%E8%8D%89%E5%B8%83%E4%B8%81%F0%9F%8C%BF%F0%9F%8D%AE/fencadnndhdeggodopebjgdfdlhcimfk
github:
https://github.com/Xdy1579883916/vanilla-pudding
> docs: Add "Vanilla Pudding" extension to homepage

- packages/wxt/src/core/zip.ts
I noticed that zipping is not done using streams which results in the zip file being accumulated in the memory of the user which massively slows down the process of zipping and for some users (me included) throws an out of heap error for big projects.
before:
after:
> perf: create zip using streams

- docs/guide/key-concepts/auto-imports.md
I found the previous wording clunky, so I tried to rephrase it while keeping the original voice.
> docs: rephrase a paragraph

- docs/.vitepress/components/UsingWxtSection.vue
MaxFocus: Link Preview extension added
> docs: Add "MaxFocus" extension to homepage

- README.md
- packages/wxt/README.md
- Updated "Get Started" to the install link
- Removed "Installation"
- Add "Changelog" since changlog is no longer in repo root
- Use `video` tag for demo so it (maybe) works on NPM?
> docs: Update README

- packages/wxt/package.json
- packages/wxt/src/core/runners/web-ext.ts
- packages/wxt/src/types/index.ts
- pnpm-lock.yaml
See https://github.com/wxt-dev/web-ext-run/releases/tag/web-ext-run-v0.2.1
> chore(deps): Upgrade `web-ext-run` (0.2.0 to 0.2.1)

- docs/.vitepress/components/UsingWxtSection.vue
Add two plugins developed using wxt: Exchange Rate Converter (one Chinese version, one international version)
> docs: Add "Exchange Rate Converter" extensions to homepage

- docs/guide/key-concepts/manifest.md
> docs: Update manifest.md

- packages/wxt/src/core/utils/building/resolve-config.ts
Adds debug log to help figure out why the vite import is failing: https://discord.com/channels/1212416027611365476/1259890091531440189/1259890091531440189
> fix: Add debug logs for vite builder

- packages/wxt/src/client/content-scripts/ui/__tests__/index.test.ts
- packages/wxt/src/client/content-scripts/ui/index.ts
- packages/wxt/src/client/content-scripts/ui/types.ts
> feat: add XPath support to getAnchor()

- docs/guide/key-concepts/frontend-frameworks.md
> docs: fix typo

- docs/.vitepress/components/UsingWxtSection.vue
Added Respond Easy plugin that allows to generate review responses with AI. Built by me
> docs: Added "RespondEasy" to homepage

- docs/get-started/compare.md
- Less word wrap
- Longer explainations
| Before | After |
|---|---|
| ![old](https://github.com/user-attachments/assets/cecc6751-6175-478d-b646-eecb2ee9f906) | ![new](https://github.com/user-attachments/assets/b9be64d1-896f-48c6-b126-6ceb89244c1f) |
If someone wants to automate the number counting or add links, by all means please do.
> docs: Extract comparison comments to footnotes

- docs/guide/extension-apis/storage.md
- packages/wxt/src/__tests__/storage.test.ts
- packages/wxt/src/storage.ts
This closes https://github.com/wxt-dev/wxt/issues/823
> feat(storage): `init` option and rename `defaultValue` to `fallback`

- docs/guide/directory-structure/app-config.md
This closes https://github.com/wxt-dev/wxt/issues/862
> docs: Fix environment variable reference

- docs/.vitepress/components/UsingWxtSection.vue
add extension to the usingWxtSection
> docs: Add "NiceTab" to homepage

- packages/wxt/package.json
- packages/wxt/src/client/content-scripts/__tests__/content-script-context.test.ts
- packages/wxt/src/client/content-scripts/content-script-context.ts
> fix(content-script-context): Fix initialization logic for Firefox

- docs/get-started/introduction.md
Just wanted to fix a small typo. The original text did not make sense.
> docs: Fix small typo in introduction

- packages/wxt/package.json
- packages/wxt/src/core/create-server.ts
- packages/wxt/src/core/utils/__tests__/number.test.ts
- packages/wxt/src/core/utils/building/resolve-config.ts
- packages/wxt/src/core/utils/env.ts
- packages/wxt/src/core/utils/number.ts
- packages/wxt/src/core/wxt.ts
- packages/wxt/src/types.ts
- pnpm-lock.yaml
refer #938 
Debounce the watcher's onChange.
> perf: Reduce hypersensitive onChange of watcher

- docs/.vitepress/components/UsingWxtSection.vue
I used Plasmo before on some extensions, but I recently found WXT and loved it, so I built an extension that had been on my list for a while.
> docs: Add "Dofollow Links for SEO" to homepage

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Add "Discord Message Translator" extension to homepage

- docs/.vitepress/components/UsingWxtSection.vue
Habit Tracker app widget for daily habit tracking
> docs: Add "Habit Tracker" to homepage

- docs/.vitepress/components/UsingWxtSection.vue
https://github.com/catppuccin/github-file-explorer-icons
Thanks for making WXT! Really great project.
> docs: Add "Catppuccin for GitHub File Explorer Icons" to homepage

- docs/.vitepress/components/UsingWxtSection.vue
repository: https://github.com/Semro/syncwatch
> docs: Add "Sync Watch" extension to homepage

- docs/.vitepress/config.ts
- docs/guide/resources/compare.md
- package.json
- patches/markdown-it-footnote.md
- patches/markdown-it-footnote.patch
- pnpm-lock.yaml
https://www.markdownguide.org/extended-syntax/#footnotes
> enhance(docs): comparison to real footnotes

- packages/i18n/README.md
- packages/i18n/src/module.ts
I have tested it with the wxt demo and it seems to work as I expected.
Does everything look good? Anything needed to change?
Closes #1108
> feat: Add support for configuring the `locales` directory

- docs/.vitepress/components/UsingWxtSection.vue
Keyword Rank Checker made with wxt
> docs: Add "Keyword Rank Checker" to homepage

- docs/.vitepress/components/UsingWxtSection.vue
Repo:
https://github.com/johnson-jnr/youtube-simple-view
> docs: Add "YouTube Simple View" to homepage

- docs/.vitepress/components/UsingWxtSection.vue
https://chromewebstore.google.com/detail/propbar-property-data-enh/pccbghdfdnnkkbcdcibchpbffdgednkf?hl=en&authuser=0
> docs: Add "propbar.co.uk" to homepage

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Add "Wandpen" to homepage

- docs/guide/essentials/content-scripts.md
https://github.com/wxt-dev/examples/blob/main/examples/inject-script/entrypoints/content.ts
> docs: Update `injectScript` docs to match example from examples repo

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Add "EyeDropper" to homepage

- packages/wxt/src/core/create-server.ts
- packages/wxt/src/core/keyboard-shortcuts.ts
- packages/wxt/src/core/runners/web-ext.ts
- packages/wxt/src/types.ts
> fix: Only show reopen browser shortcut when it can be done

- packages/wxt/src/core/builders/vite/index.ts
- packages/wxt/src/core/create-server.ts
- packages/wxt/src/core/keyboard-shortcuts.ts
- packages/wxt/src/types.ts
Attempt to fix issue here: https://discord.com/channels/1212416027611365476/1317009958113644554
> fix: Properly close readline instance on close

- docs/guide/essentials/content-scripts.md
close https://github.com/wxt-dev/wxt/issues/1341
> docs: update content script ui + svelte, svelte v4 => v5

- docs/.vitepress/components/UsingWxtSection.vue
Adding HTML to Markdown to the homepage.
Thank you
> docs:  Added "HTML to Markdown" to the homepage

- .github/FUNDING.yml
* Simplified the `.github/FUNDING.yml` file by removing placeholder comments
* Set the GitHub sponsor username only to `wxt-dev`
> chore: simplify `FUNDING.yml`

- packages/wxt/package.json
- pnpm-lock.yaml
Follow up to #1375.
???
~#1374
> fix: Allow `vite-node@^3.0.0`

- docs/.vitepress/config.ts
- docs/guide/installation.md
- docs/guide/resources/community.md
- docs/guide/resources/faq.md
Add a community page and various other links to community resources.
See website preview.
> docs: Add community page

- docs/guide/resources/faq.md
Updated an external link in FAQs
See Website Preview.
> docs: Fixed an external link in FAQs

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
Added configuration for vscode with configured default formatter and recommended extensions to work with this project
> chore: add vscode configuration

- docs/guide/resources/compare.md
Add maintenance attribute to the comparison documentation
- **CRXJS** : https://github.com/crxjs/chrome-extension-tools/discussions/974
- **Plasmo** : https://github.com/wxt-dev/wxt/pull/1404#issuecomment-2643089518
> docs: Add "maintenance" to the comparison

- docs/.vitepress/components/UsingWxtSection.vue
Python Code Runner was built with wxt. 
wxt has been a game changer for development, thank you! Everything just works.
The extension provides a Python playground in the browser, using Pyodide. [Learn more](https://cliprun.com).
> docs: Add "Python Code Runner" to homepage

- docs/guide/essentials/messaging.md
> docs: add comctx to messaging docs

- docs/guide/resources/community.md
> docs: Add `comctx` to community page

- docs/guide/essentials/content-scripts.md
Possessive pronoun "its" vs "it's"
n/a
> docs: Uses correct grammar

- .gitattributes
* Exclude template files from language statistics
> chore: improve `.gitattributes`

- .github/workflows/pr-closed.yml
Don't write thankyou comment if pr is not merged
> fix: fix `pr-closed.yml` workflow

- docs/.vitepress/components/UsingWxtSection.vue
added the extension that I made with WXT
> docs: Added monochromate to the homepage

- pnpm-lock.yaml
- pnpm-workspace.yaml
> chore(deps-dev): bump happy-dom from 15.11.4 to 17.1.8

- pnpm-workspace.yaml
> chore: update `onlyBuiltDependencies`

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Add "SnapThePrice" to the homepage

- .gitignore
- docs/.vitepress/config.ts
- docs/guide/essentials/extension-apis.md
- packages/wxt/typedoc.json
- pnpm-lock.yaml
The blog with the new RSS feed was overwriting the `buildEnd` callback setup by the knowledge plugin, so the knowledge files were never generated.
I also added required config for the new blog pages to be added to the knowledge files correctly.
https://discord.com/channels/1212416027611365476/1296842665249472614/1356324259344941076
> docs: Fix knowledge file generation

- package.json
- packages/storage/src/__tests__/index.test.ts
- packages/wxt/src/core/builders/vite/plugins/devHtmlPrerender.ts
- packages/wxt/src/core/package-managers/deno.ts
- packages/wxt/src/core/package-managers/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- taze.config.ts
- templates/react/package.json
- templates/solid/package.json
- templates/svelte/package.json
- templates/vanilla/package.json
- templates/vue/package.json
Security warnings:
- This closes https://github.com/wxt-dev/wxt/security/dependabot/18
- This closes https://github.com/wxt-dev/wxt/security/dependabot/30
- This closes https://github.com/wxt-dev/wxt/security/dependabot/29
- This closes https://github.com/wxt-dev/wxt/security/dependabot/28
- This closes https://github.com/wxt-dev/wxt/security/dependabot/27
- This closes https://github.com/wxt-dev/wxt/security/dependabot/26
- This closes https://github.com/wxt-dev/wxt/security/dependabot/25
- This closes https://github.com/wxt-dev/wxt/security/dependabot/19
Major version changes (production):
- `nypm`: `^0.3.12` &rarr; `^0.6.0`
- `ohash`: `^1.1.4` &rarr; `^2.0.11`
- `sharp`: `^0.33.5` &rarr; `^0.34.1`
- `unimport`: `^4.0.0` &rarr; `^5.0.0`
Major version changes (development):
- `oxlint`: …
> chore(deps): Update all dependencies

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Added "[Blens - Time Tracker and AI Insight]" to the homepage

- docs/guide/essentials/unit-testing.md
Updated docs to point to correct location for `injectScript`
> docs: Fix import in unit-testing.md

- docs/.vitepress/components/UsingWxtSection.vue
Added [Always Light Mode](https://chromewebstore.google.com/detail/always-light-mode/njnammmpdodmfkodnfpammnpdcbhnlcm?authuser=0&hl=en) to the homepage, to keep the site in light mode regardless of system preferences.
> docs: Added "[Always Light Mode]" to the homepage

- packages/wxt/src/core/builders/vite/index.ts
- packages/wxt/src/core/utils/__tests__/manifest.test.ts
- packages/wxt/src/core/utils/manifest.ts
Add cors setting like previous
https://github.com/user-attachments/assets/8b64b8d7-6bdf-4c1c-a0bd-b43298d86667
This PR closes #1606
> fix: Fix CORS error in Firefox

- docs/.vitepress/components/UsingWxtSection.vue
The new version of DesignPicker built with WXT
Added "[DesignPicker]" to the homepage
> docs: Added "[DesignPicker]" to the homepage

- pnpm-lock.yaml
- pnpm-workspace.yaml
Upgrade `web-ext-run` to latest, including changes to latest `web-ext` version.
```sh
cd packages/wxt-demo
pnpm dev
```
This PR closes #1426, this closes #1633
> chore(deps): Upgrade `web-ext-run` to v0.2.3

- package.json
- packages/analytics/package.json
- packages/auto-icons/package.json
- packages/i18n/package.json
- packages/module-react/package.json
- packages/module-solid/package.json
- packages/module-svelte/package.json
- packages/module-vue/package.json
- packages/storage/package.json
- packages/unocss/package.json
- packages/webextension-polyfill/package.json
- packages/wxt/package.json
- pnpm-lock.yaml
Apart of #1643. `@aklinker1/check` needed some changes to work in Bun workspaces.
> chore: Upgrade `@aklinker1/check` to v2

- packages/analytics/modules/analytics/client.ts
- packages/analytics/package.json
- packages/analytics/tsconfig.json
- packages/i18n/package.json
- packages/i18n/src/__tests__/index.test.ts
- packages/i18n/src/__tests__/types.test.ts
- packages/i18n/src/index.ts
- packages/i18n/tsconfig.json
- packages/storage/package.json
- packages/storage/src/__tests__/index.test.ts
- packages/storage/src/index.ts
- packages/storage/tsconfig.json
- pnpm-lock.yaml
Make extension API usage consistent between all packages.
> fix: Use `@wxt-dev/browser` instead of `@types/chrome`

- docs/.vitepress/components/UsingWxtSection.vue
Added my extension Tab Grab to the homepage
> docs: Added Tab Grab to the homepage

- docs/.vitepress/components/UsingWxtSection.vue
docs: Added "WeChat Markdown Editor" to the homepage
> docs: Added "WeChat Markdown Editor" to the homepage

- docs/.vitepress/components/UsingWxtSection.vue
Adds "NZBDonkey" to the docs as extension built with wxt
n/a
n/a
> docs: Added "NZBDonkey" to the homepage

- packages/wxt/src/core/builders/vite/plugins/devServerGlobals.ts
This addresses the regression mentioned here: https://github.com/wxt-dev/wxt/pull/1406#discussion_r2121977297
> fix: Support http server websocket inside containers

- docs/.vitepress/components/UsingWxtSection.vue
Adding BrowserLens extension to WXT homepage.
> docs: Added "BrowserLens" to the homepage

- packages/wxt/src/core/builders/vite/plugins/devServerGlobals.ts
Fixes https://github.com/wxt-dev/wxt/pull/1707#discussion_r2127956612
> fix: Fix bad regex from #1707

- docs/.vitepress/components/UsingWxtSection.vue
adding wechat reader enhancer in docs.
> docs: adding wechat reader enhancer in docs.

- docs/.vitepress/components/UsingWxtSection.vue
Adding new extension to home-page.
> docs: adding youtube-video-scheduler in docs.

- docs/guide/essentials/es-modules.md
Fixed a small typo in the docs
> fix: correct typos in docs

- docs/.vitepress/components/UsingWxtSection.vue
> docs: add "Piwik PRO Tracking Helper" to the home page

- packages/auto-icons/README.md
> docs: Add SVG compatibility note

- docs/.vitepress/components/UsingWxtSection.vue
Added my extension built with wxt - MultiField CopyCat
Really appreciate your work on this amazing framework! Saved me so much time!
> docs: Add "MultiField CopyCat" to homepage

- docs/.vitepress/components/UsingWxtSection.vue
> docs: Added Filmbudd Pro to the homepage

- packages/wxt/package.json
- packages/wxt/src/core/runners/web-ext.ts
- pnpm-lock.yaml
> chore(deps): Upgrade web-ext-run to support CDP

- packages/wxt/package.json
- packages/wxt/src/core/runners/web-ext.ts
- pnpm-lock.yaml
Upgrade `publish-browser-extension`, this closes https://github.com/wxt-dev/wxt/security/dependabot/18
> chore(deps): `publish-browser-extension` upgrade
