wxt-dev/wxt

demo/package.json, src/cli/commands/build.ts, src/cli/commands/dev.ts, src/cli/commands/init.ts, src/cli/commands/prepare.ts, src/cli/index.ts, src/cli/utils/defineCommand.ts
This closes #8. Also adds more support for other CLI flags, like the browser and manifest version, which were supported by build but not passed into it from the CLI.
=> feat: Support more CLI flags for `build` and `dev`

e2e/tests/manifest-content.test.ts, e2e/tests/output-structure.test.ts, src/core/build/buildEntrypoints.ts, src/core/utils/manifest.ts
Just cleaning up any unnecessary hashes from the output.
=> fix: Remove hash from content script css outputs

e2e/tests/output-structure.test.ts, scripts/build.ts, src/client/templates/reload-html.ts, src/client/templates/virtual-content-script.ts, src/client/utils/setupWebSocket.ts, src/core/types/external.ts, src/core/utils/detectDevChanges.ts, src/core/vite-plugins/devHtmlPrerender.ts, src/index.ts
This closes #2 
When changing an HTML file, instead of reloading the entire extension, just refresh the effected pages. This lets the background script and content scripts continue running without being restarted.
Vite's HMR logic doesn't work in this case because it only effects pages ending in `index.html`, so we have to do it ourselves.
=> feat: Reload HTML files individually

demo/src/entrypoints/overlay.content/index.ts, package.json, pnpm-lock.yaml, src/cli/commands/dev.ts, src/client/utils/reloadContentScript.ts, src/client/virtual-modules/background-entrypoint.ts, src/client/virtual-modules/virtual-module-globals.d.ts, src/core/build.ts, src/core/server.ts, src/core/types/external.ts, src/core/utils/__tests__/arrays.test.ts, src/core/utils/__tests__/detectDevChanges.test.ts, src/core/utils/arrays.ts, src/core/utils/detectDevChanges.ts, src/core/utils/manifest.ts, src/index.ts, src/testing/fake-objects.ts
This closes #4!
MV3: The background script can register and unregister content scripts, so we should do that as the code changes.
MV2: We can't dynamically register content scripts, ~~but we can reload the pages as they change, and they should get the new content.~~ _Edit: reloading pages won't work with `run_at`, I need to actually register the content script, and those APIs are new in MV3. So we won't be able to reload a content script without reloading an entire extension._
=> feat: Content scripts reloading

e2e/tests/output-structure.test.ts, e2e/tests/user-config.test.ts, src/core/types/external.ts, src/core/utils/manifest.ts
Types now allow passing `name`, `description`, and `version` options via `config.manifest`.
Description is also read from the manifest now.
=> fix: Some fields cannot be overridden from `config.manifest`

.github/workflows/release.yml, .github/workflows/validate.yml, bin/wxt.cjs, package.json, src/cli/index.ts
Currently, since this is a monorepo, running `pnpm i` on a fresh clone, like in CI, fails since it needs to build the binary before it can link it in the node modules for the demo project.
Instead, you have to run install twice:
```sh
pnpm install --ignore-scripts
pnpm build
pnpm install
```
If instead, the entrypoint is a JS file committed to the project, the binary can be linked on the first install.
=> chore: Simplify binary setup

.github/workflows/validate.yml, package.json
Templates broke when v0.3.1 was released because of the CSS entrypoints. The react and solid templates used `popup/index.css`, which results in two entrypoints with the same name.
https://github.com/aklinker1/wxt/actions/runs/5704132503/job/15457436014
Template validation should be ran against the current code, not the latest published version, and that will catch this sooner.
=> ci: Validate templates against `main`

.github/workflows/validate.yml, docs/get-started/introduction.md, scripts/build.ts
Types were broken after a new version of Vite was released.
https://github.com/aklinker1/wxt/actions/runs/5841845307/job/15842377107
Essentially, because I was linking the local version of WXT to the templates, it was using the node_modules from the root PNPM install inside the declaration file defining what the `wxt.config.ts` file looks like. So the vite versions were conflicting between the `wxt/node_modules` and the `wxt/templates/vue/node_modules` directories.
Simply packing the local version of WXT solves this issue because the tarball doesn't include a `node_modules` directory.
Templates weren't actually broken when using them, they were only broken in CI.
=> Fix templates

scripts/build.ts, src/core/build.ts, src/core/log/printBuildSummary.ts, src/core/log/printFileList.ts, src/core/log/printTable.ts, src/core/zip.ts
Tables now are printed in 1 log call along with their header and footer. In CI, this cleans up the alignment of the file list. In non-CI environments, this should be unnoticeable.
| Old | New |
| --- | --- |
| <img width="666" alt="Screenshot 2023-08-13 at 9 46 08 AM" src="https://github.com/aklinker1/wxt/assets/10101283/e57c16e4-9890-4b0f-9f28-61d3ea0e769b"> | <img width="645" alt="Screenshot 2023-08-13 at 9 49 07 AM" src="https://github.com/aklinker1/wxt/assets/10101283/506f5623-d493-4be7-b591-ca3b0373fdb9"> |
=> chore: Improve file list output in CI

docs/guide/manifest.md, e2e/tests/manifest-content.test.ts, src/core/utils/manifest.ts
Checkout the new docs for manifest icons. If you're extension icons are named in a supported format, they will be added to your manifest automatically.
https://wxt.dev/guide/manifest.html#icons
=> feat: Discover icons from the public directory

.github/dependabot.yml, .prettierrc.yml, demo/src/entrypoints/example.sandbox/index.html, demo/src/entrypoints/options/index.html, demo/src/entrypoints/popup.html, demo/src/entrypoints/sandbox.html, docs/guide/bookmarks.md, docs/guide/devtools.md, docs/guide/history.md, docs/guide/newtab.md, docs/guide/options.md, docs/guide/popup.md, docs/guide/sandbox.md, docs/guide/sidepanel.md, docs/guide/unlisted-pages.md, package.json, pnpm-lock.yaml, templates/react/entrypoints/popup/index.html, templates/solid/entrypoints/popup/index.html, templates/svelte/src/entrypoints/popup/index.html, templates/vanilla/entrypoints/popup/index.html, templates/vue/entrypoints/popup/index.html
`pretty-quick` does not support prettier 3, so I switch to `lint-staged`
=> chore: Upgrade to prettier 3

templates/vue/entrypoints/popup/App.vue
For some reason the import aliases weren't working in Vue. This was fixed in #95.
=> chore: Use import aliases in Vue template

src/cli/commands/clean.ts, src/cli/commands/index.ts, src/cli/index.ts, src/core/clean.ts, src/index.ts
Will delete the following directories:
- `node_modules/.vite`
- `node_modules/.cache`
- `**/.wxt`
- `.output/*`
Run `wxt prepare` or any other command to add them back.
=> feat(cli): Add `wxt clean` command to delete generated files

docs/guide/background.md, docs/guide/bookmarks.md, docs/guide/content-scripts.md, docs/guide/devtools.md, docs/guide/history.md, docs/guide/newtab.md, docs/guide/options.md, docs/guide/popup.md, docs/guide/sandbox.md, docs/guide/sidepanel.md, docs/guide/unlisted-pages.md, e2e/tests/output-structure.test.ts, src/core/build/__tests__/findEntrypoints.test.ts, src/core/build/findEntrypoints.ts, src/core/types/external.ts, src/core/utils/__tests__/entrypoints.test.ts, src/core/utils/__tests__/groupEntrypoints.test.ts, src/testing/fake-objects.ts
=> feat: Include/exclude entrypoints based on target browser

src/core/build/__tests__/findEntrypoints.test.ts, src/core/build/findEntrypoints.ts, src/core/utils/importEntrypointFile.ts, src/core/utils/strings.ts
If you have auto-imports disabled, WXT couldn't parse your entrypoints because the definition functions were missing, like `defineContentScript`, since those functions were auto-imported before. Now, we manually add those imports to the file before importing it to get it's config.
=> fix: Import client utils when getting entrypoint config

e2e/tests/init.test.ts, e2e/utils.ts, src/core/build.ts
Helps speed up windows and prevent hanging child processes
=> fix: Use `execaCommand` instead of `node:child_process`

demo/package.json, demo/src/entrypoints/example-tsx.content.tsx, demo/tsconfig.json, e2e/tests/react.test.ts, e2e/utils.ts, package.json, pnpm-lock.yaml, scripts/build.ts, src/core/utils/importEntrypointFile.ts
This closes #132
Fixed by replacing babel with esbuild inside Jiti's transform hook. Esbuild has native support for JSX, whereas babel doesn't, and Jiti doesn't provide a way to add custom babel plugins.
Should also improve performance since ESBuild is faster than babel, which jiti uses by default.
=> fix: Support loading `tsx` entrypoints

src/core/runners/__tests__/index.test.ts, src/core/runners/index.ts, src/core/runners/manual.ts, src/core/types/external.ts, src/core/utils/getInternalConfig.ts, src/core/utils/wsl.ts, templates/react/_gitignore, templates/solid/_gitignore, templates/svelte/_gitignore, templates/vanilla/_gitignore, templates/vue/_gitignore
This closes #135. New `runner.disable` field in config.
```ts
runner: {
disabled: true,
},
});
```
OR
```ts
// web-ext.config.ts - should be gitignored
defineRunnerConfig({
disabled: true
});
```
=> feat: Disable opening browser automatically during dev mode

e2e/tests/manifest-content.test.ts, e2e/tests/output-structure.test.ts, src/core/build/buildEntrypoints.ts, src/core/utils/manifest.ts, src/testing/fake-objects.ts
BREAKING CHANGE: Content script CSS used to be output to `assets/<name>.css`, but is now `content-scripts/<name>.css` to match the docs.
=> fix!: Output content script CSS to `content-scripts/<name>.css`

docs/guide/build-targets.md, e2e/tests/manifest-content.test.ts, src/core/build/findEntrypoints.ts, src/core/server.ts, src/core/types/external.ts, src/core/utils/__tests__/entrypoints.test.ts, src/core/utils/content-scripts.ts, src/core/utils/entrypoints.ts, src/core/utils/getInternalConfig.ts, src/core/utils/manifest.ts
See new E2E test for example usage. This closes #152
=> feat: Allow customizing entrypoint options per browser

.codecov.yml, .prettierignore, src/core/vite-plugins/devHtmlPrerender.ts, templates/svelte/src/entrypoints/popup/App.svelte
This closes #157.
Make sure the react-refresh preamble is added to the pre-rendered HTML file correctly. Couple of changes here:
1. Use `transformIndexHtml` hook instead of `transform`, and the preamble was added
2. Some dev scripts needed to be added to `transform` to bundle them all together before vite transforms the index.html, so I added `transform` back
3. The preamble was added as a inline script, which extension CSP's don't allow, so it had to be virtualized on the server
4. Other misc tweaks to prevent errors.
> Seeing one when opening the popup: "Failed to load url /chunks/popup-8bf139d1.js (resolved id: /chunks/popup-8bf139d1.js). Does the file exist?"
=> fix: Support `react-refresh` when pre-rendering HTML pages in dev mode

e2e/tests/manifest-content.test.ts, e2e/tests/output-structure.test.ts, e2e/tests/react.test.ts, e2e/tests/user-config.test.ts, e2e/utils.ts, src/core/utils/manifest.ts
=> fix: More consistent `version_name` generation between browsers

e2e/tests/manifest-content.test.ts, src/core/types/external.ts, src/core/utils/__tests__/content-scripts.test.ts, src/core/utils/content-scripts.ts, src/core/utils/manifest.ts
=> fix: Ignore non-manifest fields when merging content script entries

src/client/utils/ContentScriptContext.ts
Instead of extending it, we're now implementing it and creating a abort controller internally... I wonder if we should also stop using a class now, since WXT doesn't use classes internally anywhere else.
```
[wxt] The content script "example-tsx" crashed on startup! TypeError: this.setTimeout is not a function
... this.contentScriptName=I,this.options=Re,wS(this,No)&&dh(this,zo,MS).call(this),this.setTimeout(()=>{dh(this,Ho,LS).call(this)})} ...
```
For some reason, when you extend abort controller, `this` is an abort controller, not your class, in Firefox.
=> fix(firefox): Stop extending `AbortController` to fix crash in content scripts

vitest.workspace.ts
This will hopefully speed up the windows-tests job in CI.
> *Edit: Doesn't appear to have much effect, but this will improve local tests speeds as well.*
They were originally separate because the directories the tests create were conflicting, but that was solved a while back.
=> chore: Run E2E tests in parallel

e2e/tests/typescript-project.test.ts, src/core/utils/building/generate-wxt-dir.ts
`lib` is mismatched cause we manual set `lib` option so that override the default value which effected by `target` option.
=> fix!: Remove `lib` from `.wxt/tsconfig.json`

e2e/tests/typescript-project.test.ts, src/core/utils/building/generate-wxt-dir.ts
Pulled out of https://github.com/wxt-dev/wxt/pull/209#pullrequestreview-1713793601 to investigate why the snapshots are so different.
=> chore: Remove whitespace from genearted `.wxt` files

demo/src/entrypoints/background.ts, demo/wxt.config.ts, e2e/tests/typescript-project.test.ts, src/core/utils/building/generate-wxt-dir.ts, src/core/utils/building/get-internal-config.ts, src/core/utils/testing/fake-objects.ts, src/core/vite-plugins/tsconfigPaths.ts, src/types/external.ts, src/types/internal.ts
Allow adding custom aliases relative to the project's root directory.
See E2E test changes for an example.
=> feat: Add `alias` config for customizing path aliases

.github/workflows/sync-releases.yml
=> ci: Automatically sync GitHub releases with `CHANGELOG.md` on push

e2e/tests/manifest-content.test.ts, src/core/runners/web-ext.ts, src/core/utils/manifest.ts
This closes #226 
Dev mode is broken, see: https://github.com/wxt-dev/wxt/issues/230 and https://bugzilla.mozilla.org/show_bug.cgi?id=1864284
> "Firefox retains the page action API, key, and special shortcut in the developer preview but will merge the page action features into action in a later release."
> https://extensionworkshop.com/documentation/develop/manifest-v3-migration-guide/#browser-action
=> fix: Generate valid manifest for Firefox MV3

src/core/utils/building/import-entrypoint.ts
Apart of #222. Fixes one issue with getting WXT working inside bun.
=> fix: Don't use `bun` to load entrypoint config

src/core/initialize.ts
> [!WARNING]
> Bun is not 100% compatible with WXT. When running scripts, `bun run --bun wxt ...` is not supported yet. See #222 for more details.
https://github.com/wxt-dev/wxt/assets/10101283/a6db94bb-2d95-4f06-9116-bc57c606fcf3
=> feat: List `bun` as an experimental option in `wxt init`

docs/guide/manifest.md, e2e/tests/manifest-content.test.ts, src/core/utils/manifest.ts
=> feat!: Allow plural directory and only png's for manifest icons

src/core/vite-plugins/unimport.ts
Node modules are already bundled and ready to go, imports should never be added. It seems like this could be caused by several issues with unimport, but those only really happen inside node_modules.
- https://github.com/unjs/unimport/issues/270
- https://github.com/unjs/unimport/issues/223
This closes #246
=> fix(auto-imports): Don't add imports to `node_module` dependencies

e2e/tests/output-structure.test.ts, src/core/utils/building/get-internal-config.ts, src/core/utils/types.ts, src/types/external.ts
This closes #257.
```ts
import { defineConfig } from 'wxt';
outDir: "dist",
});
```
=> feat: Add config to customize `outDir`

.github/workflows/validate.yml, e2e/utils.ts
E2E tests and templates aren't apart of the PNPM workspace, so running `pnpm i` inside those folders caused the command to fail. We can use the `--ignore-workspace` flag to ignore the workspace and treat them as individual projects, speeding up those checks.
| | Before | After |
| --- | --- | --- |
| tests | 1:11 | 1:05 |
| windows-tests | 2:39 | 1:40 |
=> chore: Speed up CI using `pnpm` instead of `npm`

src/core/utils/building/__tests__/find-entrypoints.test.ts, src/core/utils/building/find-entrypoints.ts
This closes #275. I also refactored the glob detection to only find valid entrypoints in the first place, so we don't need to worry about ignored files anymore.
=> fix: Catch duplicate entrypoint names before loading their config

.github/workflows/validate.yml, src/core/builders/vite/plugins/bundleAnalysis.ts, src/core/builders/vite/plugins/cssEntrypoints.ts, src/core/builders/vite/plugins/devHtmlPrerender.ts, src/core/builders/vite/plugins/entrypointGroupGlobals.ts, src/core/builders/vite/plugins/excludeBrowserPolyfill.ts, src/core/builders/vite/plugins/globals.ts, src/core/builders/vite/plugins/multipageMove.ts, src/core/builders/vite/plugins/tsconfigPaths.ts, src/core/builders/vite/plugins/unimport.ts, src/core/builders/vite/plugins/webextensionPolyfillAlias.ts, src/core/builders/vite/plugins/webextensionPolyfillInlineDeps.ts, src/testing/wxt-vitest-plugin.ts
=> fix: Only use type imports for Vite

docs/guide/content-script-ui.md, src/client/utils/content-script-ui.ts
=> docs: Improve content script UI guide

src/__tests__/storage.test.ts, src/storage.ts
=> fix(storage): Support multiple `:` characters in storage keys

scripts/build.ts
Before, you would see progress track the number of complete build steps, like this:
```
- Building
- Building [1/4]
- Building [2/4]
- Building [3/4]
- Build complete
```
But that's not very satisfying because it never prints [4/4]! Nor does it make as much sense to me as it used to.
This PR changes these labels from printing the "number of completed steps" to the "current step in progress", which makes console output look like this instead:
```
- Building
- Building [1/4]
- Building [2/4]
- Building [3/4]
- Building [4/4]
- Build complete
```
> The first `building` line without a progress indicator is shown during build prep, while we calculate the number of build steps.
=> chore: Update `scripts/build.ts` show current build step in progress, not completed count

docs/.vitepress/components/ExampleList.vue, docs/.vitepress/theme/index.ts, docs/entrypoints/devtools.md, docs/examples.md, docs/guide/manifest.md, docs/guide/testing.md
I added [the ability to add frontmatter to examples](https://github.com/wxt-dev/wxt-examples/commit/98d37533bd9ec7c0ed2aa32048cfabbdce0e6433), so now we can filter example lists down based on the new `tag` frontmatter.
So as more examples are added, they will automatically show up on the docs website.
=> docs: Use example tags to automate relevant example lists

docs/guide/content-script-ui.md, package.json, pnpm-lock.yaml, src/client/content-scripts/__tests__/content-script-ui.test.ts, src/client/content-scripts/content-script-ui.ts
This PR introduces notable changes to the Content Script UI documentation and test suite:
1. **Documentation Update:**
Added 'Isolated Events' column to the tables in the documentation to reflect the new `isolateEvents` parameter (also add the parameter to the shadow DOM part documentation):
| Method     | Isolated Styles | Isolated Events   | HMR | Use page's context |
| ---------- | :-------------: | :---------------: | :-: | :----------------: |
| Integrated |       ❌        |         ❌        | ❌  |         ✅         |
| ShadowRoot |       ✅        | ✅ (default off)  | ❌  |         ✅         |
| IFrame     |       ✅        |         ✅        | ✅  |         ❌         |
2. **Test Code Update:**
Updated tests to verify default behavior and parameter passing for `isolateEvents`. Actual …
=> feat: Add `isolateEvents` option to `createContentScripUi`

docs/guide/development.md, src/core/utils/__tests__/manifest.test.ts, src/core/utils/manifest.ts, src/core/utils/testing/fake-objects.ts, src/virtual/background-entrypoint.ts
With the browser as the focused window, press `ctrl+E` on windows/linux and `cmd+E` on mac to reload the extension without visiting `chrome://extensions`.
This closes #321
=> feat(DX): Add `ctrl+E`/`cmd+E` shortcut to reload extension during development

src/core/utils/__tests__/manifest.test.ts, src/core/utils/manifest.ts
This closes #329.
For MV3, match patterns in the `web_accessible_resources` are not the same as content scripts. They must have a path of `/*`, nothing else.
> An array of strings, each containing a [match pattern](https://developer.chrome.com/docs/extensions/mv3/match_patterns) that specifies which sites can access this set of resources. Only the origin is used to match URLs. Origins include subdomain matching. Google Chrome emits an "Invalid match pattern" error if the pattern has a path other than '/*'.
> &ndash; https://developer.chrome.com/docs/extensions/reference/manifest/web-accessible-resources#manifest_declaration
So if the content script matches `*://play.google.com/books/*`, the `web_accessible_resources` match pattern should be `*://play.google.com/*`.
=> fix: Strip path from `web_accessible_resources[0].matches`

src/core/create-server.ts, src/core/utils/building/internal-build.ts, src/core/utils/building/rebuild.ts
Previously, we were calling it twice.
=> perf: Only call `findEntrypoint` once per build

docs/guide/entrypoints.md, src/core/utils/__tests__/test-entrypoints/imported-option.ts, src/core/utils/building/__tests__/import-entrypoint.test.ts, src/core/utils/building/import-entrypoint.ts
This closes #345. Doesn't fix the underlying issue, but improves the error message and updates the documentation to talk about the bug.
```
WXT 0.14.1                                                                                                             9:27:53 AM
ℹ Building chrome-mv3 for production with Vite 5.0.5                                                                  9:27:54 AM
✖ Command failed after 559 ms                                                                                         9:27:54 AM
[9:27:54 AM]  ERROR  logId is not defined
at importEntrypointFile (/Users/aklinker1/Development/github.com/wxt-dev/wxt/dist/cli.js:1792:13)
at async getContentScriptEntrypoint (/Users/aklinker1/Development/github.com/wxt-dev/wxt/dist/cli.js:451:35)
at async …
```
=> fix: Improve error message and document use of imported variables outside an entrypoint's `main` function

demo/src/entrypoints/background.ts, e2e/tests/typescript-project.test.ts, src/core/utils/building/generate-wxt-dir.ts
=> fix: Allow `browser.runtime.getURL` to include hashes and query params for HTML paths

docs/guide/content-script-ui.md
While going through docs the newly introduced Content Script UI function, I noticed some typos and outdated code for the Shadow Root UI examples in some languages.
=> docs: Fix typos and outdated ui function usage

src/cli.ts, src/core/utils/__tests__/entrypoints.test.ts, src/core/utils/__tests__/manifest.test.ts, src/core/utils/building/__tests__/find-entrypoints.test.ts, src/core/utils/building/__tests__/group-entrypoints.test.ts, src/core/utils/building/find-entrypoints.ts, src/core/utils/building/get-internal-config.ts, src/core/utils/testing/fake-objects.ts, src/types/external.ts, src/types/internal.ts
ref: https://github.com/wxt-dev/wxt/issues/330
Add a simple test case and passed, but I found that test cases of `src/core/utils/building/__tests__/find-entrypoints.test.ts` seems outdated, not only caused by my changes:
=> feat: Add `filterEntrypoints` option to speed up development

scripts/build.ts
=> fix: Allow requiring built-in node modules from ESM CLI

demo/wxt.config.ts, src/core/utils/__tests__/manifest.test.ts, src/core/utils/building/get-internal-config.ts, src/core/utils/manifest.ts, src/core/utils/testing/fake-objects.ts, src/types/external.ts, src/types/internal.ts
You can disable the reload command by setting the value to `false`, or customize the key binding by setting it to a custom string.
This closes #358
=> feat: Add `dev.reloadCommand` config

package.json, pnpm-lock.yaml, src/core/utils/building/internal-build.ts, src/types/modules.d.ts
=> fix: Add subdependency bin directory so `wxt build --analyze` works with PNPM

src/core/builders/vite/index.ts, src/core/create-server.ts, src/core/runners/web-ext.ts, src/core/utils/__tests__/arrays.test.ts, src/core/utils/arrays.ts, src/core/utils/building/__tests__/detect-dev-changes.test.ts, src/core/utils/building/detect-dev-changes.ts, src/types/external.ts
=> feat: Restart dev mode when saving config

src/core/builders/vite/index.ts
This closes #236.
Still facing the problem where chrome ignores loading sourcemaps by default, but the workaround is to use a custom profile with the setting disabled, as mentioned in https://github.com/wxt-dev/wxt/issues/236#issuecomment-1915049984
=> fix: Enable inline sourcemaps by default during development

docs/guide/publishing.md, package.json, pnpm-lock.yaml, scripts/build.ts, src/cli/__tests__/index.test.ts, src/cli/cli-utils.ts, src/cli/commands.ts, src/cli/index.ts, src/core/utils/building/internal-build.ts, src/core/utils/exec.ts, src/types/modules.d.ts
This closes #57!
Adds the `wxt submit` and `wxt submit init` commands. Not using the word "publish" since `npm publish` is a built-in command. Naming it submit will hopefully guide people to calling their package.json scripts "submit" as well.
=> feat: Add `submit` command

src/core/utils/building/__tests__/detect-dev-changes.test.ts, src/core/utils/building/detect-dev-changes.ts
This closes #388. See https://github.com/wxt-dev/wxt/issues/388#issuecomment-1919216744 for a description of the problem.
=> fix(dev): Reload `<name>/index.html` entrypoints properly on save

demo/src/entrypoints/background.ts, e2e/tests/output-structure.test.ts, src/core/builders/vite/index.ts, src/core/create-server.ts, src/core/utils/building/__tests__/find-entrypoints.test.ts, src/core/utils/building/__tests__/group-entrypoints.test.ts, src/core/utils/building/find-entrypoints.ts, src/core/utils/building/group-entrypoints.ts
> [!NOTE]
> This PR is being merged into a feature branch, and will not be immediately available. I plan on adding #357 to the same feature branch before doing a release.
Adding `type: "module"` to the background script definition will cause it to be included in the ESM build along side any UIs. This speeds up development, reduces bundle size, and adds support things like WASM, which requires ES modules to load (this will address #392).
> Note that even if we're using ESM for the background, we need to restart the service worker by reloading the entire extension (see #53 for more details). Since HMR doesn't really do anything for the background, so I'm not adding support for that.
=> feat!: ESM background support

demo/src/entrypoints/background.ts, src/core/builders/vite/index.ts, src/core/builders/vite/plugins/defineImportMeta.ts, src/core/builders/vite/plugins/index.ts
This fixes #392.
Vite replaces `import.meta.url` with `document.currentScript && document.currentScript.src || new URL("background.js",document.baseURI).href` by default, which crashes in background service worker since `document` isn't defined. Instead, we're now overriding the definition and replacing `import.meta.url` with `self.location.href`, which is defined in all possible JS contexts of chrome extensions.
=> fix: Don't crash background service worker when using `import.meta.url`

.github/dependabot.yml
Dependabot should also watch GitHub Actions for updates.
Ideally I would like to migrate it to [renovate](https://github.com/renovatebot/renovate) as I do find renovate a lot more extensible / useful as you can have one config for all your packages / projects in one repository and it has way more dependency checks it can do like actions, npm modules, your package.json's `packageManager` field and many more. Plus it can automerge if checks pass like tests (if enabled)
=> chore: Add dependabot for github actions

src/core/builders/vite/index.ts, src/core/builders/vite/plugins/bundleAnalysis.ts, src/core/utils/building/build-entrypoints.ts, src/core/utils/building/internal-build.ts
This closes #422. Removing `emitFile: true` removed the stats files from the vite output since they're now written to the output directory by the `fs` module instead of being added to vite's bundle (which is used to generate the build summary)
I also removed the files after the `stats.html` file is generated.
=> fix: Exclude analysis files from the build summary

src/core/utils/building/internal-build.ts, src/core/utils/building/resolve-config.ts, src/core/utils/testing/fake-objects.ts, src/types/index.ts
See #422. To add a timestamp:
```ts
analysis: {
outputFile: `stats-${Date.now()}.html`
},
});
```
=> feat: Add option to customize the analysis output filename

src/client/content-scripts/ui/__tests__/index.test.ts, src/client/content-scripts/ui/index.ts
`insertBefore` recreates the anchor element.
When using dynamic injection triggered by adding the anchor element, the browser will run into infinite loop.
and mini refactor included.
=> fix: Use `insertBefore` on mounting content script UI

e2e/tests/auto-imports.test.ts, e2e/tests/typescript-project.test.ts
| Case | Before | After |
| --- | --- | --- |
| `pnpm test run` on Windows CI | 44s | 45s |
| `pnpm test:coverage` on Linux CI | 37s | 37s |
So no actual change to test performance
=> chore(e2e): Use `wxt prepare` instead of `wxt build` when possible to speed up E2E tests

demo/package.json, package.json, pnpm-lock.yaml
Upgrading Vite to get performance improvements, related to https://github.com/wxt-dev/wxt/discussions/432#discussioncomment-8426777.
| Case | Before | After |
| :-- | :-: | :-: |
| `cd demo && pnpm build` | 1.798s | 1.607s |
> The demo app has 11 small build steps.
=> perf: Upgrade Vite to 5.1

src/client/content-scripts/ui/index.ts
According to #333, it seems `onMount` should call after the UI is mounted, and `onRemove` should call before the UI is removed, but ShadowRootUI was not.
It's inconvenient that `shadowHost` is not connected when mounting UI.
=> fix: Fix order of ShadowRootUI hooks calling

src/core/utils/building/import-entrypoint.ts
=> fix: Don't assume react when importing JSX entrypoints during build

docs/entrypoints/content-scripts.md, src/core/utils/__tests__/manifest.test.ts, src/core/utils/manifest.ts, src/types/index.ts
=> feat: Customize when content scripts are registered, in the manifest or at runtime

src/core/builders/vite/index.ts, src/core/create-server.ts, src/core/utils/building/generate-wxt-dir.ts, src/core/utils/entrypoints.ts
This closes #421 
It seems like vite logs this error when a script outside the chunks directory is mentioned in the HTML file? Not really sure why, but that was the only difference I found.
=> fix: Output main JS file for HTML entrypoints to chunks directory

src/__tests__/storage.test.ts, src/storage.ts
- Exposed `defaultValue` property on defined storage items
- Improved typing for `watch` function when a default value is present
=> feat(storage): Improved support for default values on storage items

docs/guide/storage.md, src/__tests__/storage.test.ts, src/storage.ts
Once this is merged, see https://wxt.dev/guide/storage.html#running-migrations for ensuring migrations are ran.
=> fix(storage): Only run migrations when the extension is updated

package.json, src/core/utils/building/resolve-config.ts
=> fix: Resolve the path to `node_modules/wxt` correctly

package.json, pnpm-lock.yaml, src/core/zip.ts
=> chore: Use JSZip for `wxt zip`, enabling future features

src/core/utils/building/resolve-config.ts
=> feat: Add warnings when important directories are missing

docs/guide/manifest.md, src/browser.ts, src/core/utils/__tests__/manifest.test.ts, src/core/utils/manifest.ts, src/core/utils/testing/fake-objects.ts
This closes #517.
Instead of having to use a function to change the keys between manifest versions, you can just include both the MV2 and MV3 keys in a single object. When targetting MV2, all MV3 keys will be removed. When targetting MV3, all MV2 keys will be removed.
```ts
manifest: ({ manifestVersion }) => {
const manifest = {
// ...
};
if (manifestVersion === 2) manifest.browser_action = {};
else manifest.action = {};
return manifest;
};
});
```
```ts
manifest: {
// ...,
action: {},
browser_action: {},
},
});
```
=> feat: Automatically remove top-level MV2-only or MV3-only keys

docs/guide/manifest.md, src/core/utils/__tests__/manifest.test.ts, src/core/utils/manifest.ts
This closes #490, as described in https://github.com/wxt-dev/wxt/issues/490#issuecomment-1969572568.
=> feat: Automatically generate `browser_action` based on `action` for MV2

src/core/package-managers/pnpm.ts
If a private package is in the root `package.json`, it was not discovered. Now it is, using `pnpm ls -r` instead of just `pnpm ls`. This is valid for non-workspace repos as well.
=> fix(zip): List all private packages correctly in a PNPM workspace

src/core/zip.ts
In a monorepo with multiple `package.json` files, the local modules downloaded by `zip.downloadPackages` should be relative to the `package.json` they're added to, not relative to the wxt project's root.
=> fix(zip): List `.wxt/local_modules` overrides relative to the `package.json` they're added to

README.md, docs/guide/installation.md, docs/guide/migrate-to-wxt.md
Faced with the error below when trying to use `pnpx` on my Windows machine.
`pnpx : The term 'pnpx' is not recognized as the name of a cmdlet, function, script file, or operable program.`
[ `pnpm dlx`](https://pnpm.io/cli/dlx) works fine. pnpm maker Zoltan says [`pnpx` is being deprecated in favor of `pnpm dlx`](https://stackoverflow.com/a/70266473).
=> docs: Replace `pnpx` with `pnpm dlx`

docs/guide/publishing.md
Here is my proposal for the github action in the publishing section of the documentation.
1. `Version`
Checks for changes in the `package.json` file. If there is a change, it retrieves the version of your extension.
3. `Submit`
Submits your extension to the store using the `wxt submit` command.
`pnpm` and `npm` code-group.
Here's a[ link to my CI Deploy](https://github.com/GuiEpi/plex-skipper/actions/runs/8222114482/job/22483242808) to show you how it works.
I follow the [pnpm continuous integration guide ](https://pnpm.io/continuous-integration#github-actions) and your [publishing](https://wxt.dev/guide/publishing.html) section.
=> docs: Add examples for GitHub Actions

src/core/initialize.ts
When initializing a project in a certain folder, if a `.gitignore` file exists in the project, a warning message will appear.
I still have a question, when the folder where we initialize the project contains other content, do we need to clear the content before downloading the template? 🤔
=> fix(init): Don't overwrite existing files when bootstrapping a new project

e2e/tests/init.test.ts, src/core/initialize.ts
=> chore: Add a test covering `wxt init` in a non-empty directory

src/core/create-server.ts, src/core/utils/building/build-entrypoints.ts
=> fix(dev): Don't crash dev mode when rebuild fails

e2e/tests/zip.test.ts, src/core/zip.ts, src/types/index.ts
- Fix do not [escape Vue interpolations](https://vitepress.dev/guide/using-vue#escaping)
- Add test correctly applies template variables for zip file names
=> feat: Add `{{mode}}` Template Variable

demo/wxt.config.ts, src/core/utils/building/resolve-config.ts
This closes https://github.com/wxt-dev/wxt/pull/564#discussion_r1536867522, see thread for more details.
Uses defu to apply default values instead of spread to not spread undefined values over real values. Replaced 4 spreads inside the config:
- `analysis` - This is the only object effected by CLI flags and is causing a problem today, the rest are just for safety.
- `alias`
- `experimental`
- `dev`
=> fix: Don't override `wxt.config.ts` options when CLI flags are not passed

src/core/utils/building/resolve-config.ts, src/core/utils/manifest.ts, src/core/wxt.ts, src/types/globals.d.ts, src/types/index.ts
Follow up to https://github.com/wxt-dev/wxt/pull/567#discussion_r1537069550
There is potentially more simplification that could happen, but because the directories all depend on one-another, it's not really worth it IMO. Unless there's a way to define dependent fields in defu, I won't make any further changes.
=> chore: Merge user config using `defu`

src/core/builders/vite/index.ts, src/core/builders/vite/plugins/devHtmlPrerender.ts, src/core/builders/vite/plugins/devServerGlobals.ts, src/core/create-server.ts, src/core/utils/building/build-entrypoints.ts, src/core/utils/building/internal-build.ts, src/core/utils/building/resolve-config.ts, src/core/utils/manifest.ts, src/core/utils/testing/fake-objects.ts, src/core/wxt.ts, src/types/index.ts
See https://github.com/wxt-dev/wxt/pull/577#issuecomment-2026542566. Now config is always resolved immediately at the beginning of all public APIs.
=> chore: Refactor order of config resolution

src/cli/__tests__/index.test.ts, src/cli/commands.ts, src/core/create-server.ts, src/types/index.ts
Added the `dev.port` field to `InlineConfig` to allow configuring the dev server port.
=> feat: Configure dev server port with `dev.server.port`

demo/wxt.config.ts, e2e/tests/hooks.test.ts, src/core/builders/vite/index.ts, src/core/wxt.ts, src/types/index.ts
This is useful if you need to conditionally apply config/plugins based on the build.
For example, with UnoCSS, you can add it to only entrypoints with a UI:
```ts
hooks: {
'vite:build:extendConfig': (entrypoints, config) => {
const names = entrypoints.map(entry => entry.name);
if (names.includes("popup")) config.plugins.push(UnoCSS());
},
'vite:devServer:extendConfig': (entrypoints, config) => {
config.plugins.push(UnoCSS());
},
},
});
```
This provides a solution to https://github.com/wxt-dev/wxt/issues/596
=> feat: Add hooks for extending vite config

docs/.vitepress/components/UsingWxtSection.vue
An efficient browser translation plugin that translates web text into any language, powered by AI.
=> docs: Add Fluent Read to homepage

docs/guide/extension-apis.md
is it new version,but no doc?,there is no `browser.runtime.onInstall.addEventListener` or `browser.storage.local.setItem`,but there is `browser.runtime.onInstalled.addListener` and `browser.storage.local.set`,and it does work
=> doc: Fix bad extension API examples

docs/guide/manifest.md
A single-byte space was missing from the sample comment in `wxt.config.ts` .
=> docs: Fix typo on example for wxt.config.ts.

templates/vue/wxt.config.ts
Update templates/vue/wxt.config.ts to temporarily resolve #606 #538 issue
=> chore: Update vue template config

package.json, pnpm-lock.yaml, src/client/content-scripts/ui/__tests__/index.test.ts
Fixes https://github.com/aklinker1/webext-core/issues/59
=> fix(dep): Upgrade `@webext-core/isolated-element` to v1.1.2

docs/guide/development.md
Just a fix for `chromiumArgs: ['--window-size=400x300'],` in the documentation.
`400x300` is not the correct format, should be `400,300`.
More info: https://source.chromium.org/chromium/chromium/src/+/main:headless/lib/switches.cc;l=116-117?q=kWindowSize&ss=chromium
=> FIX: Chromium window-size example format

package.json, packages/wxt/e2e/tests/output-structure.test.ts, packages/wxt/src/core/builders/vite/index.ts, packages/wxt/src/core/utils/__tests__/strings.test.ts, packages/wxt/src/core/utils/strings.ts, packages/wxt/src/types/index.ts, packages/wxt/src/virtual/content-script-isolated-world-entrypoint.ts, packages/wxt/src/virtual/content-script-main-world-entrypoint.ts, packages/wxt/src/virtual/unlisted-script-entrypoint.ts, pnpm-lock.yaml
This closes #622.
Adds support for returning values from both content scripts (likely with `registration: 'runtime'`, but not necessarily) and unlisted scripts.
Just return a value from the script's main function and the background will get the value, even if it's an async function.
```ts
// Sync function's work
export default defineUnlistedScript(() => {
// ...
return "return value"
});
// Async functions also work
export default defineUnlistedScript(async () => {
// ...
return "return value"
});
```
=> feat: Support returning values from scripts executed with the scripting API

package.json, packages/wxt-demo/wxt.config.ts, packages/wxt/e2e/tests/manifest-content.test.ts, packages/wxt/package.json, packages/wxt/src/core/builders/vite/__tests__/fixtures/module.ts, packages/wxt/src/core/builders/vite/__tests__/fixtures/test.ts, packages/wxt/src/core/builders/vite/__tests__/index.test.ts, packages/wxt/src/core/builders/vite/index.ts, packages/wxt/src/core/builders/vite/plugins/index.ts, packages/wxt/src/core/builders/vite/plugins/removeEntrypointMainFunction.ts, packages/wxt/src/core/utils/__tests__/transform.test.ts, packages/wxt/src/core/utils/building/find-entrypoints.ts, packages/wxt/src/core/utils/building/resolve-config.ts, packages/wxt/src/core/utils/package.ts, packages/wxt/src/core/utils/testing/fake-objects.ts, packages/wxt/src/core/utils/transform.ts, packages/wxt/src/types/index.ts, pnpm-lock.yaml
Entrypoint options can now be extracted during the build using the [Vite Runtime API](https://vitejs.dev/guide/api-vite-runtime). Previously, these files were loaded using `jiti`.
```ts
experimental: {
viteRuntime: true,
},
});
```
With the experimental flag enabled, you can now:
- Use imported variables outside the `main` function of your entrypoints
- Use vite-only features like `import.meta.glob` to generate options like content script `matches`
- Leverage any Vite plugins you've listed in `wxt.config.ts` to transform your code, allowing use of non-standard syntax
Since all code is now loaded using Vite, it should also be more consistent and lead to less differences in runtime, which has caused errors.
The main downside to this approach is …
=> feat(experimental): Load entrypoint options with Vite Runtime API

docs/guide/handling-updates.md
According to the TypeScript types and the docs https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onInstalled the method name should be `addListener`
=> docs: Correct event handler name in handling-updates.md

packages/wxt/src/core/runners/web-ext.ts, packages/wxt/src/types/index.ts
This will add the [`keepProfileChanges`](https://extensionworkshop.com/documentation/develop/web-ext-command-reference/#keep-profile-changes) to the runner config.
I was trying to use the `--keep-profile-changes` in the `args` but it was not working, so I added as a option for the runner, just like `startUrls`.
Usage:
```ts
import { defineConfig } from 'wxt';
...
runner: {
keepProfileChanges: true
},
});
```
or
```ts
// web-ext.config.ts
import { defineRunnerConfig } from 'wxt';
export default defineRunnerConfig({
keepProfileChanges: true
});
```
=> feat(runner): Add `keepProfileChanges` option

packages/wxt/src/core/utils/__tests__/strings.test.ts, packages/wxt/src/core/utils/strings.ts
=> fix: Remove `import * as` imports from entrypoints during build

packages/wxt/e2e/tests/zip.test.ts, packages/wxt/src/core/zip.ts
This closes https://github.com/wxt-dev/wxt/issues/604
=> fix: Allow zipping hidden files in sources by listing them explicitly in `includeSources`

packages/wxt/src/client/content-scripts/content-script-context.ts
When the content script is loaded repeatedly, `ctx.onInvalidated` does not work.
This is because the code below uses `data.type`:
https://github.com/wxt-dev/wxt/blob/7b849b80cbc1e47ff0ee34450a2fcb46a29467fa/packages/wxt/src/client/content-scripts/content-script-context.ts#L230
Whereas the events sent out by postMessage use `event` as the key.
https://github.com/wxt-dev/wxt/blob/7b849b80cbc1e47ff0ee34450a2fcb46a29467fa/packages/wxt/src/client/content-scripts/content-script-context.ts#L220
=> fix: `ctx.onInvalidated` does not work

packages/wxt/src/core/utils/building/import-entrypoint.ts
The current console error message displays an incorrect link, which results in a 404 error. Specifically, it points to: <https://wxt.dev/guide/entrypoints.html#side-effects>
Upon checking, I found that the correct link is <https://wxt.dev/guide/go-further/entrypoint-side-effects.html>, so I should quickly submit a PR to fix it.
---
Additionally, the homepage link also resulted in a 404 error yesterday. Have you been restructuring the documentation recently? Is there any linting or other validation in place to check for broken links after making adjustments to the documentation?
=> fix: To fix the issue with Entrypoint Side Effects link errors

docs/.vitepress/config.ts, docs/.vitepress/theme/custom.css, docs/.vitepress/utils/head.ts, docs/.vitepress/utils/menus.ts
This is just a little stitch-in-time PR with some menu config cleanup:
- utility functions replace raw sidebar menu config
- utility functions replace raw head config
This makes it simpler to [grok and update the sidebar menu](https://github.com/davestewart/wxt/blob/feat/docs-cleanup/docs/.vitepress/config.ts#L73) structure:
```ts
sidebar: {
'/guide/': menuRoot([
menuGroup('Directory Structure', '/guide/directory-structure/', [
menuItem('.output/', 'output'),
menuItem('composables/', 'composables'),
menuGroup('entrypoints/', '/guide/directory-structure/entrypoints/', [
menuItem('background', 'background.md'),
menuItem('bookmarks', 'bookmarks.md'),
...
]),
...
]),
}
```
Additionally, some minor style updates:
- main sidebar sections now use correct level 0 (this can be …
=> docs: Simplify menu configuration

.gitignore, package.json, packages/wxt-demo/package.json, pnpm-lock.yaml, scripts/build-deps.ts
I was getting annoyed having to rebuild wxt every time I did something with the demo. As I extract more packages from `wxt`, this will only get more annoying.
So I spent a long time today looking into NX and turborepo for caching dependency builds... Didn't like either because I had to adopt them completely to just cache builds. I have had this problem in the past, and I ended up using turborepo and using a jank setup to just cache builds. I would prefer to keep using `pnpm` for all commands, and I wanted to try something else. So I wrote a script to detect the dependency tree, and build and cache the output.
You can now declare a `build-deps` script in a package.json like so:
https://github.com/wxt-dev/wxt/blob/d5bc5ce5cf3320486e034238884281ea4d6190fc/packages/wxt-demo/package.json#L18 …
=> chore: Cache package dependency builds

packages/wxt/package.json, packages/wxt/src/core/builders/vite/plugins/devHtmlPrerender.ts, pnpm-lock.yaml
Basically, the react plugin was adding an inline script to the HTML page to enable HMR:
```html
<script type="module">
import RefreshRuntime from "/@react-refresh"
RefreshRuntime.injectIntoGlobalHook(window)
window.$RefreshReg$ = () => {}
window.$RefreshSig$ = () => (type) => type
window.__vite_plugin_react_preamble_installed__ = true
</script>
```
However, this doesn't work for chrome extensions because inline scripts are blocked by the CSP, in dev and production.
Before this PR, I had written specific code to find and virtualize this react-refresh "preamble" inline script so it could be loaded from `http://localhost:3000/@wxt:virtualized-react-refresh`.
Originally, while working on https://github.com/wxt-dev/wxt/pull/729, I wanted to extract this logic into it the new package. But since …
=> fix: Generalize react-refresh preamble logic to virtualize all inline scripts

packages/module-solid/README.md, packages/module-solid/src/index.ts
Forgot to add this from the template.
=> fix: Add `target: esnext` by default

package.json, pnpm-lock.yaml
1.0.5 switched to using `spawn` instead of `exec`, which doesn't throw an error automatically when it fails. 1.0.7 throws the error so the build fails.
=> chore(dev-deps): Upgrade @aklinker1/buildc to 1.0.6

packages/wxt/src/core/create-server.ts
I noticed when you first saved a change to the project, WXT would report `.wxt/tsconfig.json` as a changed file along with the actual file you changed. That's unnecessary, the directory doesn't effect any runtime code. So this PR ignores these files in the watcher.
| Before | After |
| --- | --- |
| <img width="611" alt="Screenshot 2024-06-19 at 8 31 54 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/561d03fa-826f-45e5-bb74-74adcd7b6967"> | <img width="507" alt="Screenshot 2024-06-19 at 8 32 10 AM" src="https://github.com/wxt-dev/wxt/assets/10101283/19f5fa54-fd4a-4cf3-ba3a-7df9c6f3a829"> |
As you can see, this was causing an unnecessary extension reload, when really, the HTML pages just needed reloaded.
=> fix: Ignore .wxt file changes in dev

packages/wxt/src/__tests__/modules.test.ts, packages/wxt/src/modules.ts
If you used `addViteConfig` in a module, it cause WXT to ignore any `vite` config from your `wxt.config.ts` file. Because I forgot to await a promise 🤦
=> fix(modules): `addViteConfig` ignored user vite config

packages/wxt/src/cli/__tests__/index.test.ts, packages/wxt/src/cli/commands.ts, packages/wxt/src/core/clean.ts, packages/wxt/src/core/utils/building/resolve-config.ts
1. `wxt clean` now removes output directory contents based on the config instead of `.output`, and also improvement on the command (config, logger, etc.); also a question here why we only remove its sub dirs but keep generated zips?
2. `wxt zip` now exclude output directory for firefox sources by default since user may specify a `outDir` that does not start with a dot and it's annoying to specify it again in `excludeSources` manually
=> fix: Respect custom `outDir` when cleaning and zipping

packages/wxt/src/virtual/utils/reload-content-scripts.ts
This closes #781
Instead of throwing an uncaught error and being reported to the `chrome://extension` page...
<details>
</details>
Just log a warning:
=> fix(dev): Catch error when attempting to reload a tab in a saved tab group

docs/guide/key-concepts/manifest.md
docs example: mainfest -> manifest
=> docs: typo manifest word

packages/wxt/e2e/tests/__snapshots__/auto-imports.test.ts.snap, packages/wxt/src/builtin-modules/unimport.ts
This PR adds a name field in ESLint v9 autoImports config.
The name is used in error messages and the config inspector to help identify which configuration object is being used.
Refs:
- [Configuration Naming Conventions](https://eslint.org/docs/latest/use/configure/configuration-files#configuration-naming-conventions)
=> fix: Add missing name to ESLint v9 autoImports config

docs/guide/go-further/vite.md
closes #798 
I removed the specifics, but I'm unsure if you want to go into more detail on why plugins wouldn't work as expected.
We should make searching easier by adding a `vite-plugin` tag or standardizing issue titles like "[VITE-PLUGIN] {name of plugin}"
=> doc: detail issues with vite plugins

packages/wxt/src/core/utils/building/resolve-config.ts, packages/wxt/src/types/index.ts
This closes #759. Already had internal config for this, just adding user config.
=> feat(config): `dev.server.hostname`

packages/wxt/src/core/utils/building/generate-wxt-dir.ts
This lets the project setup module augmentation for types other than user config, like app config: https://github.com/wxt-dev/wxt/blob/c0e9fbbb0e18d274a2912488907ea0a3f19c48d3/packages/analytics/modules/analytics/index.ts#L8-L12
=> fix(modules): Add types from all wxt node_modules, not just ones with config

packages/wxt/src/core/utils/manifest.ts, packages/wxt/src/storage.ts, packages/wxt/src/types/index.ts
The link to guide page was broken and has been corrected.
=> docs: fix links to Guide pages

packages/module-svelte/README.md
The link to unimport was vue.ts, so corrected it to svelte.ts.
=> docs: fix link to unimport

packages/wxt/src/core/utils/building/generate-wxt-dir.ts
Before, if you listed a `default_locale` in your manifest, WXT would throw an error if you didn't provide a `public/_locales/{default_locale}/messages.json` file. This PR removes this requirement.
Instead of having WXT do this validation, we'll just let the browser report the problem when the extension is installed instead. This is because  it could be perfectly valid to not have a file there but because a module or some other custom build step adds translations to the output directory.
=> fix: Don't throw error if localization file is missing

packages/wxt/src/core/builders/vite/plugins/resolveAppConfig.ts
=> fix: Externalize app config during dependency optimization

packages/wxt/src/types/index.ts
I noticed that if you define the hooks object the type requires you to set all hooks which isn't correct
=> fix: wrong module hook type

docs/guide/go-further/entrypoint-loaders.md, docs/public/_redirects, packages/wxt-demo/src/entrypoints/background.ts, packages/wxt-demo/wxt.config.ts, packages/wxt/e2e/tests/manifest-content.test.ts, packages/wxt/src/core/builders/vite/index.ts, packages/wxt/src/core/utils/building/resolve-config.ts, packages/wxt/src/core/utils/testing/fake-objects.ts, packages/wxt/src/types.ts
BREAKING CHANGE: Switch from using `jiti` to import entrypoints during the build process by default to `vite-node`.
To continue using `jiti`, add the following to your `wxt.config.ts` file:
```ts
entrypointLoader: "jiti",
})
```
NOTE: "jiti" is deprecated and will be removed in the next major version, `v0.20.0`.
---
This closes #506
=> feat!: Use `vite-node` to load entrypoints by default

docs/.vitepress/config.ts, docs/guide/upgrade-guide/wxt.md, packages/wxt/CHANGELOG.md, scripts/bump-package-version.ts
This will make it easier for me to prepare migration steps for breaking changes. Before, I had to add the steps after the release, now I can add them before it, with more markdown extensions at my disposal.
=> docs: Add upgrade guide and breaking changes

packages/wxt-demo/src/entrypoints/main-world.content.ts, packages/wxt/e2e/tests/remote-code.test.ts, packages/wxt/package.json, packages/wxt/src/core/builders/vite/index.ts, packages/wxt/src/core/builders/vite/plugins/removeEntrypointMainFunction.ts, packages/wxt/src/core/utils/building/find-entrypoints.ts, packages/wxt/src/core/utils/environments/browser-environment.ts, packages/wxt/src/core/utils/environments/environment.ts, packages/wxt/src/core/utils/environments/extension-environment.ts, packages/wxt/src/core/utils/environments/index.ts
This closes #864 . It introduces the concept of an "environment". There are two environments:
- browser environment: Just contains web globals like `window` or `document`
- extension environment: browser environment + `chrome` and `browser` globals.
WXT spins up the extension environment when importing entrypoints.
=> fix: web globals not defined when importing entrypoints

packages/wxt/e2e/tests/output-structure.test.ts, packages/wxt/package.json, packages/wxt/src/core/builders/vite/plugins/removeEntrypointMainFunction.ts, packages/wxt/src/core/utils/__tests__/transform.test.ts, packages/wxt/src/core/utils/transform.ts, packages/wxt/src/sandbox/define-background.ts, packages/wxt/src/sandbox/define-unlisted-script.ts
Remove any code from entrypoint file that isn't directly related to returning the options.
https://github.com/wxt-dev/wxt/blob/0c273df271d187640a442d91f25c43a4cb2d7902/packages/wxt/src/core/utils/transform.ts#L3-L18
You can see how the entrypoints are transformed when passing the `--debug` flag: 
```
⚙ vite-node transformed entrypoint /home/aklinker1/Development/github.com/wxt-dev/wxt/packages/wxt-demo/src/entrypoints/background.ts                                                                                                                                    2:54:05 PM
⚙ Original: …
```
=> pref: Tree-shake unrelated code inside `vite-node` entrypoint loader

packages/wxt/src/core/utils/__tests__/transform.test.ts, packages/wxt/src/core/utils/transform.ts
Basically, tree-shake out any unused functions or variables that were called in the main function of an entrypoint, and nowhere else. Was already doing this with imports, now we're doing it with all top-level declarations.
See tests for examples:
https://github.com/wxt-dev/wxt/blob/26ced9319bb6c0b5ee9419eba3c6ec9f831cb3a8/packages/wxt/src/core/utils/__tests__/transform.test.ts#L121-L134
https://github.com/wxt-dev/wxt/blob/26ced9319bb6c0b5ee9419eba3c6ec9f831cb3a8/packages/wxt/src/core/utils/__tests__/transform.test.ts#L93-L113
=> fix: Remove unused top-level functions and variables when loading entrypoints with the `vite-node` loader

packages/wxt/src/core/wxt.ts
This closes https://github.com/wxt-dev/wxt/issues/873.
This does cause `vite-node`'s dev server to run in different modes when doing `wxt` vs `wxt build`, but I don't expect that to cause any problems.
=> fix: Don't default to dev mode for production builds when using `vite-node` loader

packages/auto-icons/package.json, packages/module-react/package.json, packages/module-solid/package.json, packages/module-svelte/package.json, packages/module-vue/package.json
This PR adds more metadata to make the modules more complete in terms of "required" data that's shown on npm, perhaps we should add more metadata @aklinker1?
=> chore: add more metadata for npm

packages/wxt/src/storage.ts
Just fixing some storage API links
=> docs: add missing `extension-apis` segment

packages/wxt/src/core/utils/building/find-entrypoints.ts
=> fix: do not clear `.wxt/tsconfig.json` in `findEntrypoints` if it exists

packages/wxt/e2e/tests/zip.test.ts, packages/wxt/src/core/zip.ts
I omitted `dot: true` and didn't touch the default `excludeSources` (mentioned in https://github.com/wxt-dev/wxt/issues/738#issuecomment-2192251866) to avoid filtering all files inside hidden directories (including those in `.git`). For example, in my repo:
- `dot: true` filters 4657 files
- only 1028 files are filtered with this PR
In theory, there should be no difference for the end user - both approaches will not include files inside the hidden directory if only that directory is specified in `includeSources` (i.e. to include all files inside `.hidden-dir`, you should specify `.hidden-dir/**`, not `.hidden-dir`). Perhaps this specific aspect should be mentioned somehow in the `includeSources` JSDoc?
=> feat: allow zipping hidden files by listing them explicitly in `includeSources`

packages/wxt/src/core/utils/building/resolve-config.ts, packages/wxt/src/core/utils/testing/fake-objects.ts, packages/wxt/src/core/zip.ts, packages/wxt/src/types.ts
Allows the user to exclude files when zipping the folder, real world use case for this would be excluding sourcemaps for example when using the sentry plugin you need to have them but when zipping the actual extension I don't want to have them to not "expose" the structure of my codebase.
I didn't add the include option since you can do that using the public folder
I am not quite sure about the JSDoc, had to escape it like this, anyone know a proper fix for that?
=> feat: allow excluding files when zipping

packages/wxt/src/core/utils/building/find-entrypoints.ts
This fixes https://github.com/wxt-dev/wxt/discussions/913
=> fix: Typo in sidepanel options (`browse_style` → `browser_style`)

packages/wxt/e2e/tests/typescript-project.test.ts, packages/wxt/src/core/utils/building/generate-wxt-dir.ts
This fixes: https://discord.com/channels/1212416027611365476/1272982191764144248/1272982191764144248
> I inspected the generated types and it's a bunch of function overloads where `messageName` is basically a literal string that can be passed through as argument to `.getMessage()`. It's nice for development and auto-completion, but it doesn't allow me to pass a template string with an argument that is typed correctly.
> 
> It allows me to write it as:
> ```ts
> browser.i18n.getMessage('mode_upscale')
> ```
> 
> Also this works:
> ```ts
> const myMode = 'upscale'
> browser.i18n.getMessage(`mode_${myMode}`)
> ```
> 
> But this does not (on type level):
> ```ts
> const modeOptions = modes.map((mode) => ({
>   label: browser.i18n.getMessage(`mode_${mode}`),
> }))
> ```
> 
> Am I doing …
=> fix(types): Don't report type errors when using string templates with `browser.i18n.getMessage`

packages/wxt/src/core/builders/vite/index.ts, packages/wxt/src/core/create-server.ts
related #866 
I noticed an over-firing of `resolveConfig` due to `reloadOnChange`, so I will fix that.
At first, I thought need to cache the `resolveConfig`, but don't need to cache it now. This change will reduce build time. And I haven't figured out the cause……but after repeating the launch a few times, launch speed also faster. (The 1st launch still a little slow) 🤷 
1. `cd wxt-demo`
2. `pnpm i` (rebuild the project)
3. run 1st: `node ./node_modules/wxt/bin/wxt.mjs`
- browser launch duration about 1.3s
4. repeat run 2nd..3rd..: `node ./node_modules/wxt/bin/wxt.mjs`
- browser launch duration about 600ms
- decreased
=> perf: Ignore non-source code from the file watcher

packages/wxt/src/core/builders/vite/plugins/extensionApiMock.ts
Apart of #868. If you're using Vitest, the following code is now ran automatically in a setup file: 
https://github.com/wxt-dev/wxt/blob/4570d23ed5b0a31073422aa9897e046fbc6c1f8c/packages/wxt/src/core/builders/vite/plugins/extensionApiMock.ts#L52-L56
This allows you to use packages that depend on these globals in your tests with zero config.
=> fix(testing): Stub `chrome` and `browser` globals with `fakeBrowser` automatically

packages/wxt/src/testing/wxt-vitest-plugin.ts
Before, if a WXT module added an alias to the config, Vitest wouldn't know about it. Now, when setting up the test environment, WXT is loaded like it would be during the dev command, allowing modules to run.
=> feat(testing): Load modules when setting up test environment

packages/wxt/e2e/tests/typescript-project.test.ts, packages/wxt/src/core/utils/building/generate-wxt-dir.ts
If you added an alias to a file in the `.wxt` directory, it wouldn't start with `./path/to/file`, it would start with `path/to/file`. TS requires files start with "./" or "../", so that's what this PR does.
=> fix: Ensure TSConfig paths start with `../` or  `./` so they are valid

packages/wxt/src/core/builders/vite/index.ts
From my research on https://github.com/wxt-dev/wxt/discussions/866#discussioncomment-10373242. Add the watcher config to the base config. This will make it ignored on `importEntrypoint`'s vite server. The performance is slightly more stable because vite is internally handled by the watcher.
=> perf: Ignore output directories in all `vite.watcher`

packages/wxt/src/browser/chrome.ts, pnpm-lock.yaml
After this PR, the recommended approach to importing types is this:
```ts
import { Runtime } from 'wxt/browser';
function onMesasge(message: any, sender: Runtime.Sender) {
// ...
} 
```
```ts
function onMesasge(message: any, sender: browser.runtime.Sender) {
// ...
} 
```
=> chore(types): Cleanup types in wxt/browser/chrome

packages/wxt/src/core/initialize.ts
fix #943
I think ungh is useful but problematic if the init command depends on a ~~3rd party~~ unofficial API. We don't need to use ungh to get public repository, because don't need a token even with GitHub REST API.
https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content
> This endpoint can be used without authentication or the aforementioned permissions if only public resources are requested.
=> fix: #943 avoid using ungh, switch to GitHub official REST API

docs/.vitepress/components/UsingWxtSection.vue
- draftly for linkedin also uses wxt
- we would like to showcase it in wxt home page.
- https://chromewebstore.google.com/detail/draftly-for-linkedin/fcffekbnfcfdemeekijbbmgmkognnmkd
=> docs: Add "Draftly" to homepage

packages/wxt/e2e/tests/output-structure.test.ts, packages/wxt/package.json, packages/wxt/src/core/utils/__tests__/strings.test.ts, packages/wxt/src/core/utils/strings.ts, packages/wxt/src/core/zip.ts, pnpm-lock.yaml
This closes #948. Added `scule` for better camelCase IIFE variable names, that has been annoying me whenever I noticed them lol.
=> fix: Allow adding multiple hyphens in an entrypoint name

packages/wxt/src/core/utils/building/rebuild.ts
I was logging about the #938 and noticed this.
The `BuildOutput.publicAssets` is increasing with each rebuild. `publicAssets` should not need to be merged like `BuildOutput.steps` because the current implementation is making copies.
```sh
[12:12:06] WXT 0.19.8
[12:12:07] ✔ Started dev server @ http://localhost:3000
[12:12:07] ℹ Pre-rendering chrome-mv3 for development with Vite 5.3.5
[12:12:08] ✔ Built extension in 812 ms
├─ .output/chrome-mv3/manifest.json               1.04 kB  
├─ .output/chrome-mv3/popup.html                  636 B    
├─ .output/chrome-mv3/background.js               126.73 kB
├─ .output/chrome-mv3/chunks/popup-BxzUToPe.js    8.16 kB  
├─ .output/chrome-mv3/content-scripts/content.js  133.94 kB
├─ .output/chrome-mv3/icon/128.png                3.07 kB  
├─ …
```
=> fix: duplicate `BuildOutput.publicAssets`

packages/wxt/e2e/tests/user-config.test.ts, packages/wxt/package.json, packages/wxt/src/types.ts, pnpm-lock.yaml
This closes #521
Properties like `key`, which were missing before, are now typed properly.
I am NOT marking this as a breaking change because the only change is to types... the runtime behavior hasn't changed. If this breaks peoples types, I'll fix them by adding custom typings.
=> feat: Use `@types/chrome` for config manifest type

packages/wxt/vitest.config.ts, packages/wxt/vitest.globalSetup.ts, packages/wxt/vitest.setup.ts
Separated from #966 .
Cleanup the `e2e/dist` after all tests.
=> chore: Cleanup leftover E2E test artifacts 

packages/wxt/src/types.ts
This PR fixes types from #969
Because Chrome's manifest types have an index signature `[key: string]: any`, `Omit<chrome.runtime.ManifestV3, ...>` becomes
```ts
{
[x: string]: any;
[x: number]: any;
}
```
and only the added properties remain in `UserManifest`
=> fix: fix config manifest type

.github/workflows/pkg.pr.new.yml
This PR will enable continuous publish wxt packages for every commit & PR on main automatically, instead of publishing it manually using npm command. It would be super easy and fast for testing locally, just update package version pointed to specific commit. It works in my fork, result like this ⬇️
All u need to do is [install the Github Application](https://github.com/apps/pkg-pr-new).
Detail see https://github.com/stackblitz-labs/pkg.pr.new
=> feat: continuous publish using pkg.pr.new

templates/svelte/package.json
When adding shadcn-svelte, I discovered that the template project's type was not set to "module," causing errors when using "export default" in postcss.js. Since ESM is now widely popular, shouldn't setting "type: module" by default be fine?
=> chore(package): set type to "module" for Svelte template

docs/guide/directory-structure/entrypoints/content-scripts.md
The type of `allFrames` is a boolean, not an array.
=> docs: Correct the type example of `allFrames`

docs/.vitepress/components/UsingWxtSection.vue
Add the new plugin "社媒助手" developed based on wxt。
chrome webstore: https://chromewebstore.google.com/detail/dbichmdlbjdeplpkhcejgkakobjbjalc
github: https://github.com/iszhouhua/social-media-copilot
=> docs: Add "social-media-copilot" to homepage

docs/.vitepress/components/UsingWxtSection.vue
We have recently migrated our popular browser extension, ChatGPT Writer (with over 700k downloads), from Plasmo to WXT and would like to showcase it in your portfolio. We also wrote about our migration process, which you can read here: https://chatgptwriter.ai/blog/migrate-plasmo-to-wxt
=> docs: Add "ChatGPT Writer" to homepage

packages/wxt/src/core/utils/env.ts
Makes environment variables defined in`.env.*` files take precedence over variables defined in `.env` file.
From [`dotenv` docs](https://github.com/motdotla/dotenv?tab=readme-ov-file#path):
> Pass in multiple files as an array, and they will be parsed in order and combined with process.env (or option.processEnv, if set). The first value set for a variable will win, unless the options.override flag is set, in which case the last value set will win. If a value already exists in process.env and the options.override flag is NOT set, no changes will be made to that value.
=> fix: Reverse env files priority

packages/wxt/src/core/zip.ts
Addresses issue found in https://discord.com/channels/1212416027611365476/1290394666860019794/1290546365335605338
=> fix: Use directory name when `zip.name` and `package.json#name` are not provided

packages/wxt/CHANGELOG.md
I misconfigured my privacy settings, so my email address was made visible
=> chore: remove email from changelog

packages/i18n/src/__tests__/build.test.ts, packages/i18n/src/build.ts
You may run your i18n files through ai and ai may not be perfect it may introduce undefined or null values this changes gives more human friendly output for the developer to more easily fix the problem
=> [UPDATE] error friendly messages for null and undefined values

packages/i18n/src/__tests__/index.test.ts, packages/i18n/src/__tests__/types.test.ts, packages/i18n/src/index.ts, packages/i18n/src/types.ts
Remove the final `options` argument after the substitutions array. It's documentation without Chrome was minimal, and Firefox errored out when passing it to `browser.i18n.getMessage`.
=> fix!: Remove invalid options argument

.github/workflows/publish-docs.yml, package.json, packages/wxt-demo/package.json, packages/wxt/package.json, pnpm-lock.yaml
This PR shrinks down on the dependencies we don't use and also disables the `publish-docs.yml` from running on forks.
=> chore: shrink down on dependencies

packages/wxt/e2e/tests/user-config.test.ts, packages/wxt/src/core/resolve-config.ts, packages/wxt/src/types.ts
Closes #1069
This pull request introduces a new feature to allow customization of the output directory structure using a template string. The main changes include adding a new configuration option, updating the build logic to respect this new option, and adding tests to ensure the feature works as expected.
* [`packages/wxt/src/types.ts`](diffhunk://#diff-d28c2725d1b8ea5238aee0b3d8e6c8aabdee0772ea03a560fcfe685561727f0cR56-R68): Added a new configuration option `outDirTemplate` to the `InlineConfig` interface, allowing users to define a template string for the output directory. This template can include variables such as `{{browser}}`, `{{manifestVersion}}`, `{{mode}}`, `{{modeSuffix}}`, and `{{command}}`.
* [`packages/wxt/src/core/resolve-config.ts`](diffhunk://#diff-ff0465c3a486d3ba187204 …
=> feat(config): Add `outDirTemplate` for customizing output directory structure

docs/guide/essentials/config/hooks.md, docs/guide/essentials/wxt-modules.md, packages/wxt/src/core/resolve-config.ts, packages/wxt/src/core/wxt.ts
=> fix: Ensure consistent hook execution order and add docs

packages/wxt/src/types.ts, templates/react/wxt.config.ts, templates/solid/wxt.config.ts, templates/svelte/wxt.config.ts, templates/vanilla/wxt.config.ts, templates/vue/wxt.config.ts
Goal here is to onboard more projects onto the API to make sure it works before switching the default for everyone
=> chore: Enable `extensionApi: chrome` in template projects

packages/wxt/src/core/resolve-config.ts, packages/wxt/src/types.ts
This is not being merged into `main`, but the `v0.20.0` staging branch.
---
BREAKING CHANGE: The build mode is now apart of the output directory:
- `--mode production` &rarr; `.output/chrome-mv3` (unchanged)
- `--mode development` &rarr;`.output/chrome-mv3-dev` (dev builds are output with the "-dev" suffix)
- `--mode other` &rarr;`.output/chrome-mv3-other` (all other build modes are output with the "-[mode]" suffix)
To revert back to the old behavior and output all builds to the same directory, set the `outDirTemplate` option:
```diff
+ outDirTemplate: "{{browser}}-mv{{manifestVersion}}",
});
```
⚠️ ***If you use `--user-data-dir` in your runner config***, be aware that [`web-ext` is a little buggy when you change the output directory of an …
=> fix!: Add suffix to non-production output directories

packages/wxt/src/client/content-scripts/content-script-context.ts
Noticed in a few of my extensions I was getting an error "Couldn't access property 'signal' of undefined" in production builds. Was fixed by patching WXT to remove the #private members of the context class.
Every time I use classes in JS, I end up regretting it SMH.
=> fix: Don't use `#private` member variables in `ContentScriptContext`

docs/guide/essentials/config/environment-variables.md, packages/wxt/src/core/resolve-config.ts, packages/wxt/src/core/utils/env.ts
Adds ability to prioritize browser-specific environment settings when resolving configuration.
The `mode` and `browser` files will have highest precedence, followed by the rest as they exist today.
```
.env.[mode].[browser]
.env.[mode].[browser].local
```
=> feat(env): Load env from `.env.[browser]` variants

docs/guide/essentials/project-structure.md
As for now, when you click on the "Environment Variables" anchor on the
https://wxt.dev/guide/essentials/project-structure.html
doc page it will redirect you to
https://wxt.dev/guide/essentials/config/runtime.html#environment-variables
Notice the "#environment-variables" which might be a deprecated anchor for this doc.
This Pull-Request will correct the redirect to the actual "Environment Variables" doc page.
=> docs: fix wrong anchor to "Environment Variables"

packages/i18n/src/module.ts
Editor autosave (triggered by delays or loss of focus) may save **incomplete files** if a user pauses to think or switches tabs, leading to parse failures in `updateLocalizations` during HMR. **Uncaught errors** in `updateLocalizations` then cause the whole app to crash, which is undesirable.
Error handling has now been added to prevent this.
Closes #1115
=> fix: Prevent app crashes from parse errors due to incomplete file saves

packages/wxt/src/core/utils/building/find-entrypoints.ts
=> docs: Fix typo in `popup` and `options` EntrypointOptions (#1121)

docs/guide/essentials/content-scripts.md
Fix incorrect syntax for MatchPattern. Because MatchPattern doesn't have a 'matches' function
=> docs: fix incorrect syntax for MatchPattern

packages/wxt/src/core/runners/web-ext.ts
close https://github.com/wxt-dev/wxt/issues/435
Before
After
ref: https://developer.chrome.com/blog/self-xss#can_you_disable_it_for_test_automation
=> feat: automatically disable 'Show warning about Self-XSS when pasing code' in new chrome

packages/unocss/src/index.ts
CC @Timeraa . We forgot to add the parameter to the first plugin instance. Already have it for the other a couple of lines down.
=> fix: Respect `configOrPath` for dev server

packages/wxt-demo/src/entrypoints/background.ts, packages/wxt/e2e/tests/typescript-project.test.ts, packages/wxt/src/core/generate-wxt-dir.ts
@aklinker1 
Fixes #984 
This seems to be working as you mentioned we need to change `getPathsDeclarationEntry` function only.
Do let me know your thoughts.
=> fix: Add / to PublicPath and browser.runtime.getURL

packages/module-react/modules/react.ts, packages/module-react/package.json, packages/module-solid/modules/solid.ts, packages/module-solid/package.json, packages/module-vue/package.json, packages/module-vue/src/index.ts, packages/wxt/src/core/wxt.ts
Follow up to #1177 fixing all the other modules usage of "ready".
=> fix: Use `config:resolved` hook to update config instead of `ready`

packages/wxt-demo/wxt.config.ts, packages/wxt/package.json, packages/wxt/src/core/builders/vite/index.ts, packages/wxt/src/core/create-server.ts, packages/wxt/src/core/resolve-config.ts, packages/wxt/src/core/utils/building/__tests__/detect-dev-changes.test.ts, packages/wxt/src/core/utils/building/detect-dev-changes.ts, packages/wxt/src/core/wxt.ts, packages/wxt/src/types.ts, pnpm-lock.yaml
This close #857, #863, #939.
There were lots of callbacks and dependencies between variables in the `createServer` function... I was able to clean it up apart of this PR! Very happy about that, wasn't sure how I would work around that...
I don't have E2E tests for dev mode, so we'll need to check over this carefully.
=> fix: Re-initialize WXT modules correctly during development

packages/wxt/src/core/resolve-config.ts, packages/wxt/src/core/utils/__tests__/manifest.test.ts, packages/wxt/src/core/utils/manifest.ts, packages/wxt/src/core/utils/testing/fake-objects.ts, packages/wxt/src/types.ts
BREAKING CHANGE: Remove deprecated option, `transformManifest`. Use the [`build:manifestGenerated` hook](https://wxt.dev/api/reference/wxt/interfaces/WxtHooks.html#build-manifestgenerated) to transform the manifest instead.
```diff
- transformManifest(manifest) {
-   // ...
- },
+ hooks: {
+   build:manifestGenerated: (_, manifest) =>  {
+     // ...
+   },
+ },
});
```
=> fix!: Remove `transformManfiest` option

templates/svelte/src/entrypoints/popup/main.ts
using `new App()` no longer works in Svelte 5. I updated the example template to Svelte 5. Though there is still a type error which can be fixed using this. But I just reckoned the code would've been too complicated.
```ts
const target = document.getElementById("app");
let app;
if (target) {
app = mount(App, { target });
} else {
throw new Error("Target element not found");
}
```
I found this after finding where it doesn't work. This is actually my first time using wxt so I took a while for it as I really want to use Svelte.
=> chore: Update Svelte template to Svelte 5

templates/vue/README.md
TypeScript Vue Plugin (Volar) has been deprecated and is no longer required for Vue 3 projects.
Vetur only works with Vue2 and has not been updated for 1 year.
There should be no need to mention them in templates.
=> chore(vue-template): remove references to Vetur and TypeScript Vue Plugin (Volar)

packages/storage/src/index.ts
=> fix: use `browser` for mv2 storage

packages/wxt/package.json, pnpm-lock.yaml
Apart of #1214, everything seems in order. Vanilla template works in dev mode and production builds with no errors or warnings.
Plugins haven't updated their peer dependencies yet, so it's hard to test on full projects. Will let people open issues if it doesn't work for them.
=> fix: Update `vite` dependency range to support v6

packages/wxt/src/client/content-scripts/ui/index.ts
fix #1218
Empty the child elements when removing. ref: https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren
=> fix: Correctly remove child elements with integrated UI remove

docs/guide/essentials/scripting.md, packages/wxt/src/core/utils/content-scripts.ts, packages/wxt/src/core/utils/manifest.ts, packages/wxt/src/types.ts
This better supports adding content scripts via the scripting APIs while using `registration: "runtime"`. Updated the docs to reflect this.
=> fix: Make content script `matches` optional

docs/typedoc.json, package.json, pnpm-lock.yaml, templates/vue/README.md
Only affects routes generated by typedoc
https://vitepress.dev/reference/default-theme-edit-link#frontmatter-config
=> doc: remove dead links generated by vitepress

packages/wxt/src/core/utils/manifest.ts, packages/wxt/src/core/utils/testing/fake-objects.ts
Closed https://github.com/wxt-dev/wxt/issues/1202
This limitation only exists in Chrome. I tried to load 10 suggested keys in Firefox MV2 and no error occurred.
=> fix: correct `dev.reloadCommand` restriction to consider only commands with suggested keys

packages/module-svelte/src/index.ts
See #1228. This fixes an error in dev mode:
=> fix: Modify dev `vite.resolve.conditions` to support Vite 6 + Svelte 5

docs/guide/essentials/target-different-browsers.md, packages/wxt/src/core/utils/building/__tests__/find-entrypoints.test.ts, packages/wxt/src/core/utils/building/__tests__/group-entrypoints.test.ts, packages/wxt/src/core/utils/building/find-entrypoints.ts, packages/wxt/src/core/utils/building/group-entrypoints.ts, packages/wxt/src/types.ts
Before, `findEntrypoints` only returned entrypoints that weren't skipped (excluded from build). Now, it returns all entrypoints with `skipped` set properly. This will help implement #1238.
`groupEntrypoints` is not responsible for filtering out skipped entrypoints when it generates the build steps.
=> chore: Refactor `findEntrypoints` to return all entrypoints with `skipped` set properly

packages/wxt/src/client/content-scripts/__tests__/content-script-context.test.ts, packages/wxt/src/client/content-scripts/content-script-context.ts
Fixes some type issues when using `ctx.addEventListener`.
=> types: Add overloads to `ContentScriptContext#addEventListener` for different targets

docs/.vitepress/components/UsingWxtSection.vue
Hi,
I want to add _aesthetic Notion, styled_ extension entry.
The [Chrome web store url](https://chromewebstore.google.com/detail/aesthetic/npgghjedpchajflknnbngajkjkdhncdo).
Elevate your Notion with this Chrome extension to customize headings and add a unique, aesthetic touch to your digital space.
💥 Make your Notion titles Pop!
=> docs: Add "aesthetic Notion, styled" to homepage

packages/wxt/e2e/tests/dev.test.ts, packages/wxt/src/core/wxt.ts
=> fix: Prevent changing dev server port when reloading config

packages/wxt/src/core/create-server.ts
This closes #1252. Reorder things so the init event listener up is added before the browser is opened. Seems like Chome on Arch/Linux starts up the service worker before the `buildAndOpenBrowser()` promise resolves.
=> fix: Ensure content scripts are registered immediately in dev mode

docs/guide/essentials/es-modules.md
https://vitepress.dev/guide/markdown#colored-diffs-in-code-blocks
=> docs: fix colored-diff in es-modules.md

packages/wxt/src/client/content-scripts/custom-events.ts, packages/wxt/src/core/utils/building/import-entrypoint.ts
[As mentioned on discord](https://discord.com/channels/1212416027611365476/1224505556346212515/1316157389048778783), content script output unnecessarily includes the entire `import.meta.env` object, including values from your .env file (only ones prefixed with `VITE_` or `WXT_`, which are already included elsewhere in your extension):
This PR fixes this. Basically, this happens when you reference `import.meta.env` instead of `import.meta.env.VAR_NAME`.
We were doing this because of the old Jiti import method, which used CJS, and thus `import.meta.env` was undefined. Fixed this by telling Jiti to replace `import.meta.env.XYZ` with the environment variable value instead.
=> fix: Exclude entire `import.meta.env` object from content script output

packages/wxt/src/utils/content-script-ui/shadow-root.ts, packages/wxt/src/utils/content-script-ui/types.ts
BREAKING CHANGE: Before, if you use `createShadowRootUi`, some styles set on the webpage's `html` element would effect your UI in the shadow root. By default, WXT now applies a CSS reset to prevent your UI from inheriting any styles from the webpage.
Double check that your `createShadowRootUI` UIs are styled properly. If not:
- Continue inheriting styles like before by passing `inheritStyles: true`:
```diff
const ui = await createShadowRootUi({
+ inheritStyles: true,
// ...
})
```
- Remove any manual resets for styles that were effecting your UI. For example:
```diff
/* entrypoints/reddit.content/styles.css */
- body {
-   /* Override Reddit's default "hidden" visibility */
-   visibility: visible !important;
- }
```
This is a fairly low-impact breaking change. If you needed this reset, …
=> feat!: Reset inherited styles inside shadow root

packages/module-svelte/src/index.ts
This closes #1274. For svelte, `resolve.conditions` needs to be `"browser"` for both dev and production builds. Additionally, the mode, usually "development" or "production", needs to be passed in the conditions to prevent [`esm-env`](https://www.npmjs.com/package/esm-env) from complaining.
=> fix: Svelte production errors and warnings on resolve conditions

packages/wxt/src/core/keyboard-shortcuts.ts
We were using a `boolean` and an `object|undefined` to track if keyboard shortcuts were listening, simplified to just the `object|undefined`.
=> chore: Simplify keyboard shortcuts

packages/module-react/package.json, pnpm-lock.yaml, templates/react/package.json
Follow up to #1280, this closes #1268. It actually updates the module and template to latest versions with react 19 support. No breaking changes, this upgrade is backwards compatible.
=> fix: Use react 19 in `@wxt-dev/module-react` and `templates/react`

docs/.vitepress/theme/custom.css
No,` rgba(#0b8a00 / .14)` is not a valid CSS value.
I haved update the vlaue to use RGB value with opacity for easy to update in future.
---
but here is alternative also if you prefer to use hex value with Alpha.
`rgba(#0b8a00 / .14)` to `#0b8a0024`
`rgba(#67d45e / .14)` to `#67d45e24`
Multiply the decimal opacity by 255 (e.g., `0.14 * 255 = 35.7`), approx 36 
Convert the number to a two-digit hex (36 in decimal is 24 in hex).
=> docs: Fix invalid CSS color

packages/wxt/src/core/utils/__tests__/validation.test.ts, packages/wxt/src/core/utils/validation.ts
This fixes https://github.com/wxt-dev/wxt/pull/1220#issuecomment-2561702875
=> fix: Allow runtime registered content scripts to not have `matches`

.github/workflows/release.yml, .github/workflows/sync-releases.yml, docs/guide/resources/upgrading.md, packages/webextension-polyfill/README.md, packages/webextension-polyfill/build.config.ts, packages/webextension-polyfill/entrypoints/content/index.ts, packages/webextension-polyfill/entrypoints/popup/index.html, packages/webextension-polyfill/entrypoints/popup/main.ts, packages/webextension-polyfill/modules/webextension-polyfill/browser.ts, packages/webextension-polyfill/modules/webextension-polyfill/index.ts, packages/webextension-polyfill/package.json, packages/webextension-polyfill/tsconfig.json, pnpm-lock.yaml
This module provides a way to continue using the `webextension-polyfill` after v0.20.0.
=> feat: Add `@wxt-dev/webextension-polyfill` module

packages/wxt/src/types.ts
Add back a type to prevent a breaking change.
=> fix: Add back `ExtensionRunnerConfig` as deprecated

docs/.vitepress/components/UsingWxtSection.vue
ZenGram is a Chrome/Firefox extension that selectively blocks elements of Instagram Web. it's proudly built with WXT, and I'd like to add it as a part of the WXT homepage :)
it's also open-source under MIT, at https://github.com/abhigyantrips/ZenGram.
=> docs: Added "ZenGram" to the homepage

packages/wxt/src/core/runners/web-ext.ts
The browser console does not currently open on Firefox, because wxt is passing the wrong property to web-ext. The property is called `browserConsole` but wxt was passing `console`. 
See https://github.com/mozilla/web-ext/blob/master/src/cmd/run.js#L25
=> fix(web-ext): Correctly pass `browserConsole` option to open devtools in Firefox

packages/wxt/src/utils/content-script-ui/shadow-root.ts
I saw the Discord announcement and tried it and found that shadow RootUi was broken. I found the `browser` import missing(`loadCss` failed), so I fix that.
With this fix both my project and wxt-demo mount fine.
=> fix: missing browser in shadow-root file

packages/unocss/README.md
This PR does:
1. Add option `excludeEntrypoints` examples and cleanup `entrypoints`'s, cause there is no option `entrypoints`
2. Fix `UnoCSSOptions` link url
=> docs: Fix unocss readme

docs/guide/essentials/content-scripts.md
According to the documentation for injectScript(), it requires web_accessible_resources to be defined in the manifest file
(here https://github.com/wxt-dev/wxt/blob/main/packages/wxt/src/client/inject-script.ts#L16).
However, this is missing from the current documentation. I have added the missing details.
P.S. I also verified that the script does not run without defining web_accessible_resources.
=> docs: Add missing web_accessible_resources to `injectScript` example

packages/wxt/src/client/content-scripts/ui/__tests__/index.test.ts, packages/wxt/src/client/content-scripts/ui/index.ts
fix: #1349
As reported in the Issue, missing handling of cases that already existed the anchor at initialization.
Correctly mounted in both navigation and reloading.
https://github.com/user-attachments/assets/5f143456-7bb0-47f6-976c-5ebe49abb008
=> fix: Attempt to mount at autoMount initialization

packages/i18n/README.md
Add typescriptreact as part of the I18n Ally Extension's languageIds as most translations occur in .tsx code.
This allows the translation to be displayed in tsx properly.
=> docs: Add react language ID to README

docs/guide/essentials/content-scripts.md
As shown in the picture, a bracket is missing, quickly submit a PR to fix it.
=> docs: Add missing bracket in example

packages/storage/src/__tests__/index.test.ts, packages/storage/src/index.ts
Though it is easy to call browser.storage.clear() to clear all the items, I guess it is needed to support clear in wxt storage. So I add this method.
=> feat: Add `storage.clear`

templates/vue/entrypoints/popup/style.css
This fix removes some duplicated rules on the style.css file on the Vue template.
=> Fix: Remove duplicated css rule from vue template

packages/module-svelte/package.json, pnpm-lock.yaml
Bump dependencies.
(This bumps _the lockfile_ to Vite v6, which could be an issue)
???
This PR closes #1374.
=> fix: Upgrade `vite-plugin-svelte` to support Vite 6

.github/CODEOWNERS
This PR adds a CODEOWNERS file first referenced in #1370 as a suggestion. It may also be useful to require a PR review (can be enforced as a rule in the repo settings)
=> chore(repo): add CODEOWNERS

docs/.vitepress/components/UsingWxtSection.vue
Add "Youtube Live Chat Fullscreen" to homepage
[github link](https://github.com/daichan132/Youtube-Live-Chat-Fullscreen)
[chrome extension link](https://chromewebstore.google.com/detail/youtube-live-chat-fullscr/dlnjcbkmomenmieechnmgglgcljhoepd)
=> docs: Add "Youtube Live Chat Fullscreen" to homepage

docs/guide/essentials/config/browser-startup.md
Fixing simple typo on the docs (`your` instead of `you're`)
- https://wxt.dev/guide/essentials/config/browser-startup.html#profile-customization
[your ](https://www.dictionary.com/browse/your) vs [you're](https://www.dictionary.com/browse/you're)
=> docs: fix typo `you're` -> `your`

packages/wxt/src/core/wxt.ts
I think this fix is self-explanatory, but let me know if you need clarification.
1. Add an expression that uses `import.meta.env.DEV` (or a statement wrapped with an `if (import.meta.env.DEV)` condition)
2. Build with `pnpm build --mode=development`
3. Notice how, without this PR, `import.meta.env.DEV` unexpectedly resolves to false.
=> fix: respect `inlineConfig.mode` when setting NODE_ENV

packages/wxt/src/core/utils/__tests__/manifest.test.ts, packages/wxt/src/core/utils/manifest.ts
`manifest.manifest_version` is not how you configure the target manifest version. This PR ignores the option if set (previously, it overwrote the target `manifest_version`, [as described in the issue](https://github.com/wxt-dev/wxt/issues/1388)) and logs a warning telling you that it is configured wrong.
See unit tests. No manual testing required.
This PR closes #1388.
=> fix: Ignore `manifest.manifest_version` option and warn about incorrect usage

packages/wxt/package.json, packages/wxt/src/core/resolve-config.ts, pnpm-lock.yaml
I have a local clone of WXT which I make fixes on and link into my web extension project for manual testing. My project is using a "WXT module" which is not being found by the current logic (before this PR). The reason is that WXT does a basic `import(…)` of each string in the `modules` array, which doesn’t work when the `wxt` package is symlinked into the project.
I thought about using [import-meta-resolve](https://www.npmjs.com/package/import-meta-resolve) for a more comprehensive solution. For simplicity, I went with the same approach you took with `resolveWxtModuleDir` which is just using `createRequire` from the `node:module` API.
=> fix: resolve wxt modules from the root

.github/actions/setup/action.yml, .github/workflows/pkg.pr.new.yml, .github/workflows/publish-docs.yml, .github/workflows/release.yml, .github/workflows/sync-releases.yml, .github/workflows/validate.yml, .github/workflows/vhs.yml
* Added descriptive step names and emojis in various workflows to enhance readability
* Ensured consistent formatting across all workflows for a unified look
=> ci: Enhance GitHub Actions workflows

packages/wxt-demo/src/entrypoints/ui.content/index.ts, packages/wxt-demo/src/entrypoints/ui.content/manual-style.css, packages/wxt/src/core/utils/building/__tests__/detect-dev-changes.test.ts, packages/wxt/src/core/utils/building/detect-dev-changes.ts
This PR for the #1062. The user modified file path has no suffix, and the moduleIds path written in the import syntax has a suffix. So it was unmatched and dev server no-changes.
I've changed the code style a bit. If you don't like it, please modify it to your liking.
1. cd wxt-demo && pnpm dev
2. edit & save `src/entrypoints/ui.content/manual-style.css`
3. check reload and apply new styles.
This PR closes #1062
=> fix: Properly detect and reload changed files when using Vite's `?suffix` imports

docs/guide/essentials/assets.md
Vite doesn't support aliases in HTML tags, like `<img src="~/assets/example.png">`, and our examples showed that it did.
I also added examples for Vue and JSX (react, solid, etc)
This PR closes #1440
=> docs: Fix bad alias usage in assets examples

packages/i18n/package.json, packages/module-react/package.json, packages/module-solid/package.json, packages/module-svelte/package.json, packages/module-vue/package.json, packages/storage/package.json, packages/wxt/package.json
* Added funding URL to the following packages:
- i18n
- module-react
- module-solid
- module-svelte
- module-vue
- storage
- wxt
I left out the packages that @Timeraa is authored because I don't know if it should be sponsored or an organization
Your NPM package will have the following button:
=> chore: Add funding links to `package.json` files

packages/wxt/package.json, packages/wxt/src/core/utils/env.ts, pnpm-lock.yaml
[PR #978](https://github.com/wxt-dev/wxt/pull/978), released in [v0.19.10](https://github.com/wxt-dev/wxt/releases/tag/wxt-v0.19.10),
broke variable expansion in dotenv files, a Vite built-in feature.
I encountered this while migrating from v0.18.2 to the latest.
Since already defined variables in process.env take presedence,
the call to dotenv-expand by vite won't have any effect. Calling
dotenv-expand ourselves to mimic what vite does restores the lost
functionality.
Vite has a slightly more complex env loading logic, so these changes
won't bring 100% parity, but should be good for most use-cases.
See: https://github.com/vitejs/vite/blob/642d528b7b403eb91c67ff809ffa0fb99a1ff56e/packages/vite/src/node/env.ts
I've tested this in production already by applying the very same
changes with …
=> fix: regression on variable expansion in dotenv files

docs/.vitepress/config.ts, package.json, pnpm-lock.yaml
Adds a chatbot to the docs website (video from test before it was added to WXT):
[wxt-ask-ai-demo.webm](https://github.com/user-attachments/assets/b865babe-0cdb-4591-8d99-8200905940ba)
The chat won't function on netlify PRs. CORS will block any request you try and make to the API.
It will work if you run `pnpm docs:dev` and open the docs locally at http://localhost:5173
You can also view the server's OpenAPI docs here: https://knowledge.wxt.dev/swagger
N/A
=> docs: Add AI assistant to https://wxt.dev

packages/wxt/e2e/tests/npm-packages.test.ts, packages/wxt/src/core/builders/vite/index.ts, packages/wxt/src/core/builders/vite/plugins/bundleAnalysis.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Until #1411 is ready, this allows projects to use newer versions of vite. IT DOES NOT RESOLVE THE SECURITY ISSUE, that's what #1411 is for. But I've ran into some snags there and haven't had much time to work on it, so it hasn't ben merged after a month. So I'm releasing this just to allow people to upgrade.
Run the demo extension in dev mode. This PR also upgrades the local version of Vite used during development to `6.2.0`, which would break without this change.
Related to:
- https://github.com/wxt-dev/wxt/issues/1360
- https://github.com/wxt-dev/wxt/issues/1362
But doesn't resolve them. Just applies an unsafe, temporary workaround.
=> fix: Allow vite 6.0.9+

.github/workflows/pkg.pr.new.yml, .github/workflows/vhs.yml
When I fork the repository and synchronize the upstream code, the related actions will fail to run. Therefore, I think the related actions should be prevented from running in the forked repository.
=> ci: prevent action running on forks

docs/guide/resources/migrate.md
Adds migration guide for people coming over from CRXJS.
Read through the migration notes and let me know if anything is confusing: https://deploy-preview-1430--creative-fairy-df92c4.netlify.app/guide/resources/migrate.html#crxjs
This PR closes #1405
=> docs: Add CRXJS migration docs

packages/storage/src/index.ts
One thing I noticed is that the migration will run regardless of if the current version is the desired version, e.g. if the current version is 2 and the target version is also 2 I can still see the debug message in console like
```
@wxt-dev/storage] Running storage migration for local:settings: v2 -> v2 background.js:652:19
[@wxt-dev/storage] Storage migration completed for local:settings v2 
```
I don't think there's any reason to not return early if the version matches, as the array below will have zero element anyway.
```ts
const migrationsToRun = Array.from(
{ length: targetVersion - currentVersion },
(_, i) => currentVersion + i + 1,
);
```
=> fix: Return early if no migration is needed

packages/wxt/src/core/utils/__tests__/manifest.test.ts, packages/wxt/src/core/utils/manifest.ts
Allow scripts to not register with manifest.json for MV2
add scripts to not register with manifest.json for MV2. now it builds successfully.
This PR closes #1428
=> fix: Support `registration: "runtime"` for MV2

docs/guide/essentials/config/manifest.md
The docs for config/manifest/host_permissions was showing a copy-pasted code example from config/manifest/permissions. I changed the example to one that's accurate for the host_permissions field.
n/a, it's just docs
n/a
=> Correct "Host permissions" docs showing a code example for "permissions"

pnpm-lock.yaml, pnpm-workspace.yaml
Following https://antfu.me/posts/move-on-to-esm-only, the unjs ecosystem is now ESM only.
This means that we need to extend our range of supported package versions.
Notably, I didn't upgrade ohash, because v2 removes `murmur` in favor of `digest`. (Which is ironic, because that's why I started this PR).
Other notes:
- We're already ESM-only.
- #1501 will also help with this, as buildc is also pulling in old unjs versions (but only internally, of course).
- There are other outdated deps, but I only did unjs because they were partially updated in #1496.
- unjs now offers an alternative to `import-meta-resolve` called `exsolve`. I'd leave that for another PR.
Shouldn't be needed, these are all just ESM-only migrations.
None
=> chore(deps): Bump unjs ecosystem

packages/storage/src/__tests__/index.test.ts, packages/storage/src/index.ts
Following https://github.com/wxt-dev/wxt/pull/1513 part of https://github.com/wxt-dev/wxt/pull/1511.
This PR introduces a new option `onMigrationComplete` to the storage `defineItem` that has two parameters, the migrated item and the migrated version.
Note: there might be conflicts and I will resolve when one is merged.
I have added a unit test case for the new option `onMigrationComplete`
This PR closes #1503
=> feat(storage): Add `onMigrationComplete` callback

packages/storage/src/__tests__/index.test.ts, packages/storage/src/index.ts
Part of https://github.com/wxt-dev/wxt/pull/1511, to remove console log/debug from the storage.
This PR closes https://github.com/wxt-dev/wxt/issues/1503
=> feat(storage): Add `debug` option to enable migration logs

.vscode/settings.json, packages/wxt/src/core/utils/__tests__/transform.test.ts, packages/wxt/src/core/utils/transform.ts
#1485 
support:
- `const [a, b] = [1, 2];`
- `const { x, y: renamedY, z = 3 } = someObject;`
- `const { foo: { bar } } = nested;`
- `const { unused, ...rest } = obj;`
run **packages/wxt/src/core/utils/__tests__/transform.test.ts**.
#1485 
This PR closes #1485
=> fix: Don't remove top-level destructured variable definitions when importing entrypoints

packages/wxt/e2e/tests/__snapshots__/auto-imports.test.ts.snap, packages/wxt/src/builtin-modules/unimport.ts
Add type annotation for auto-imports (ESLint 9). If typechecked, `eslint.config.js` may pop an error:
```js
The types of 'languageOptions.sourceType' are incompatible between these types.
Type 'string' is not assignable to type 'SourceType | undefined'.ts(2322)
```
On a project running checks on JS, IDE should not show squiggly lines
No related issue
=> fix: add JSDoc type annotation to auto-imports for ESlint

docs/guide/essentials/config/environment-variables.md, packages/wxt-demo/wxt.config.ts, packages/wxt/e2e/tests/typescript-project.test.ts, packages/wxt/src/core/resolve-config.ts, packages/wxt/src/core/utils/globals.ts, packages/wxt/src/core/utils/testing/fake-objects.ts, packages/wxt/src/types.ts
Currently, `import.meta.env.BROWSER` is typed as a string, which, while technically correct from a type system perspective, can be limiting in practical development. An extension might only support a specific set of browsers, such as "chrome" | "firefox".
Instead of a string, defining BROWSER as an enum-like type could offer several advantages. TypeScript's controw flow analyze makes this approach particularly useful. For instance, a switch statement on import.meta.env.BROWSER would no longer require a default case. The absence of a default case is beneficial because it prevents potential oversights when adding support for new browsers like "edge" in the future. With an enum-like type, the type checker would enforce the addition of a new case in all relevant locations.
add …
=> feat: type-safe `import.meta.env.BROWSER` with new `targetBrowers` config

docs/.vitepress/components/UsingWxtSection.vue
Adds the [radiofrance extension](https://chromewebstore.google.com/detail/radiofrance/gdjampjdgjmbifnhldgcnccdjkcoicmg) to the list of projects using WXT in the documentation
=> docs: add radiofrance extension to usingWXT

packages/wxt/src/core/builders/vite/plugins/devHtmlPrerender.ts
This bug cause of `ohash` v2 hash function change.
`ohash` hash function uses SHA256, so `Number(hashid)` return `NaN`. So I replaced it to `hash(hashId)`.
If reuse `murmurhash`, wait to merge https://github.com/unjs/ohash/pull/158
This PR closes #1578
=> fix: Fix hashing issue with inline scripts

docs/guide/essentials/entrypoints.md
In the example  browser.action.onClick is not a valid method but browser.action.onClicked is what that's available 
I have just updated entrypoint.md file and things work as intended
I know this is a bit unprofessional to raise directly a PR, I wouldn't coming from a conventional route, so reject it at your own perusal
=> updating entrypoints.md

packages/wxt/src/core/builders/vite/plugins/devHtmlPrerender.ts
This PR adds the ability for the user to use ignore attributes, either `vite-ignore` or `wxt-ignore` in html elements to make wxt ignore those elements and not process the src or href attributes.
If `wxt-ignore` is used as attribute, the attribute is removed. The `vite-ignore` attribute does not need to be removed as it is removed later by Vite.
Add the attribute `vite-ignore` or `wxt-ignore` to a `link` element in an entrypoint html file. The `href` attribute should not be processed in the resulting html file and the `vite-ignore` or `wxt-ignore` should be removed.
N/A.
Manually ignoring elements may be beneficial in some specific edge cases like in the problem which was discussed here: #1548
=> feat: ignore elements with a vite-ignore or wxt-ignore attribute

packages/storage/src/__tests__/index.test.ts, packages/storage/src/index.ts
Currently, the second signature of `WxtStorage.defineItem` method is incorrect that it doesn't respect the fallback value.
https://github.com/wxt-dev/wxt/blob/4c35798dbaaf96983d1148544716568beae41732/packages/storage/src/index.ts#L748-L754
The following examples show the bug clearly.
```typescript
export const storageTodoItems = storage.defineItem<StorageTodoItem[]>(
'local:StorageTodoItems',
{ fallback: [] },
)  // Type is StorageTodoItem[]
export const storageTodoItems = storage.defineItem<StorageTodoItem[]>(
'local:StorageTodoItems',
)  // Type is StorageTodoItem[] | null
export const storageTodoItems = storage.defineItem<StorageTodoItem[]>(
'local:StorageTodoItems', {}
)  // Type is StorageTodoItem[]. Wrong!!!
```
```typescript
export const storageTodoItems = …
```
=> fix: fix typescript error on `defineItem` fallback

docs/guide/essentials/content-scripts.md
> Cannot find name 'app'. Did you mean 'App'? `ts(2552)`
https://svelte.dev/docs/svelte/imperative-component-api#unmount
```ts
import { mount, unmount } from 'svelte';
import App from './App.svelte';
const app = mount(App, { target: document.body });
// later
unmount(app, { outro: true });
```
=> docs: fix svelte app unmount code

docs/guide/essentials/config/environment-variables.md
I'm not sure if this is a bug or intended but if it's not a bug and the docs just need to updated, hopefully this is correct. I also removed the deprecated chromeApi key.
=> docs: Update environment-variables.md with info about env.DEV

docs/guide/essentials/i18n.md
Fixing docs to call use the `rootDir`, not the `srcDir` when configuring the `public/_locales` directory.
N/A
N/A
=> fix: rootDir, not srdDir for public/_locales

docs/.vitepress/components/UsingWxtSection.vue
Request to add "PIPX - Take Control of Picture-in-Picture, Automatically" extension to the "Who's Using WXT?" section in the homepage.
=> docs: add "PIPX" to the home page

docs/.vitepress/components/UsingWxtSection.vue
Request to add "Add QR Code Generator Icon Back To Address Bar" extension to the "Who's Using WXT?" section in the homepage.
=> docs: add "Add QR Code Generator Icon Back To Address Bar" to the home page

CONTRIBUTING.md, docs/guide/essentials/entrypoints.md
Fixed the content script example code which was using `defineBackground` instead of `defineContentScript`.
Also fixed a small typo in CONTRIBUTING.md
=> docs: correct content script example code

packages/runner/src/browser-paths.ts
Added alternative path for Zen Browser that Homebrew uses
https://github.com/Homebrew/homebrew-cask/blob/main/Casks/z/zen.rb#L23C13-L23C19
Uninstall Zen and install via homebrew
```sh
brew install zen --cask
wxt -b zen
```
None that I know of
This PR closes nothing
=> feat(config): add browser path for Zen via Homebrew

packages/runner/src/browser-paths.ts
When I tried `pnpm test` locally for #1806, I saw this error:
```
FAIL  src/__tests__/options.test.ts > Options > firefoxArgs > should log a warning when --remote-debugging-port is passed in
Error: Could not find "chrome" binary.
If it is installed in a custom location, you can specify the path with the browserPaths option.
❯ Module.resolveRunOptions src/options.ts:63:11
```
My `/Applications` folder contained `Google Chrome.app` instead of `Chrome.app` (it was installed via `homebrew` a while ago). Adding an alternative path to `KNOWN_BROWSER_PATHS` resolved the error. I also added the second path for Chrome Canary just in case.
`pnpm test` stopped showing the above error.
NA
=> fix: improve Chrome path search

packages/auto-icons/README.md, packages/auto-icons/src/index.ts
Adds an icon overlay option in addition to grayscale in development environments.
>When an icon is black and white, the grayscale indicator doesn't cut it. This new one should be more obvious, and work for bw icons.
Here's the sample output:
Deprecates the previous option `grayscaleOnDevelopment` but is backward compatible, and retains the same default.
Add this option in your extension's `wxt.config.ts`
```
autoIcons: {
developmentIndicator: 'overlay',
}
```
=> feat: Add overlay option for dev icons

packages/wxt/src/core/runners/web-ext.ts
This fix enable to setup a fixed port to enable easy debugging with VSCode or other IDEs
Everything was already there, I've just added the line to pass the parameters sets in wxtUserConfig to the web-ext runner.
* Set `chromiumPort` in wxt.config.ts.
* Launch `npm run dev`
* Browse to chrome://version
* Check that `remote-debugging-port` is the same as set in config file
You can also setup a fully working environment with this repo https://github.com/sylvaneau/wxt-react-vscode-template and try to debug your project with VSCode.
This PR closes #52
=> fix: adding missing chromiumPort parameter in web-ext.ts to enable fixed port debugging

packages/runner/src/browser-paths.ts
Added browser paths for both Arc & Dia chromium browsers by the Browser Company
Install Arc & Dia browsers
```sh
wxt -b dia
wxt -b arc
```
I couldn't find one
This PR closes nothing
=> fix(paths): add browser paths for Arc & Dia on macos

.github/workflows/release.yml
Branch protection rules have been disabled because our release action pushes to the `main` branch. This PR adds a deploy key to the publish workflow to allow CI to bypass the rules and push the version/changelog to `main`.
https://github.com/sbellone/release-workflow-example
=> ci: Use deploy key to bypass branch protection rules

packages/wxt/src/utils/content-script-context.ts
This PR fixes an incorrect type definition in `ContentScriptContext.addEventListener` with Document targets.
Previously, the method signature defined the parameter as:
```ts
addEventListener<TType extends keyof DocumentEventMap>(
target: Document,
type: keyof DocumentEventMap,
handler: (event: DocumentEventMap[TType]) => void,
options?: AddEventListenerOptions,
): void;
```
Here, type was hardcoded as `keyof DocumentEventMap` instead of using the generic `TType`.
This caused type inference issues when registering event listeners, making TypeScript report incompatibility errors (e.g., with click handlers typed as `PointerEvent`).
The fix updates the method signature to:
```ts
addEventListener<TType extends keyof DocumentEventMap>(
target: Document,
type: TType,
handler: (event: …
```
=> fix(types): use TType for DocumentEventMap key in ctx.addEventListener

scripts/list-unreleased-commits.sh
I have been known to forget to release packages after PR are merged... The new script will list all the commits for a package since it's last release. You can then easily decide which packages need released.
For example, I forgot to release #1771 and that caused someone to report https://github.com/wxt-dev/wxt/issues/1866.
```plaintext
$ ./scripts/list-unreleased-commits.sh
...
----------------------------------------
Package: module-vue
Commits since last tag (module-vue-v1.0.2):
7a814724 (origin/main, origin/HEAD, main) chore(deps): Upgrade all dev dependencies (#1876)
9399d8df chore: Create script for managing dependency upgrades (#1875)
a6eef643 chore(deps): Upgrade typescript from 5.8.3 to 5.9.2
e7db1195 chore: wxt & @wxt-dev/module-vue support Vite 7 (#1771)
6f970efd chore: Upgrade …
```
=> ci: Create script to list unreleased commits for each package

packages/wxt/e2e/tests/output-structure.test.ts, pnpm-lock.yaml
I deleted the `pnpm-lock.yaml` file and all the project `node_modules` folders, then reinstalled them with `pnpm i`. That will upgrade all subdpendencies to the latest compatible version. No risk for deployments on this one, it only effects contributors and upgrades to what a new WXT extension would be installing.
=> chore(deps): Upgrade project subdependencies

packages/wxt/src/core/utils/env.ts
dotenv@17.0.0 prints “tip: 📡 auto-backup env with Radar: https://dotenvx.com/radar” ads by default, which is very annoying and needs to be turned off.
https://github.com/motdotla/dotenv/commit/b1d4a78198151ca4ef525b1fb5f77e2636622e5f
```
❯ pnpm why dotenv
Legend: production dependency, optional only, dev only
devDependencies:
@wxt-dev/auto-icons 1.1.0
└─┬ wxt 0.20.11 peer
├─┬ c12 3.2.0
│ └── dotenv 17.2.2
├── dotenv 17.2.2
├─┬ dotenv-expand 12.0.3
│ └── dotenv 16.6.1
└─┬ publish-browser-extension 3.0.2
└── dotenv 16.6.1
wxt 0.20.11
├─┬ c12 3.2.0
│ └── dotenv 17.2.2
├── dotenv 17.2.2
├─┬ dotenv-expand 12.0.3
│ └── dotenv 16.6.1
└─┬ publish-browser-extension 3.0.2
└── dotenv 16.6.1
```
=> fix: wxt normal logs are drowned by `dotenv@17.0.0` ads
